### ISSUE TITLE
Evaluating "+1" in REPL produces a Java exception

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1053]

**Comment by npasserini** [comment]
>>> +1
     WVM Error in line  (1): +1:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.uqbar.project.wollok.interpreter.operation.WollokDeclarativeNativeUnaryOperations.lambda$1(WollokDeclarativeNativeUnaryOperations.java:50)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:751)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:186)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:245)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:134)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.lambda$0(WollokInterpreterEvaluator.java:139)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:627)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:536)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evalAll(WollokInterpreterEvaluator.java:141)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:183)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:200)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:245)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:134)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator._evaluate(WollokLauncherInterpreterEvaluator.java:68)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:198)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.interpret(WollokInterpreter.java:153)
	at org.uqbar.project.wollok.launch.repl.WollokRepl.executeInput(WollokRepl.java:164)
	at org.uqbar.project.wollok.launch.repl.WollokRepl.startRepl(WollokRepl.java:89)
	at org.uqbar.project.wollok.launch.WollokLauncher.doSomething(WollokLauncher.java:61)
	at org.uqbar.project.wollok.launch.WollokChecker.doMain(WollokChecker.java:83)
	at org.uqbar.project.wollok.launch.WollokLauncher.main(WollokLauncher.java:37)
Caused by: org.uqbar.project.wollok.interpreter.core.WollokProgramExceptionWrapper
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:329)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:182)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:245)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:134)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.lambda$0(WollokInterpreterEvaluator.java:139)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:627)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:536)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evalAll(WollokInterpreterEvaluator.java:141)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:640)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:156)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:245)
	at org.uqbar.project.wollok.interpreter.AbstractWollokCallable.eval(AbstractWollokCallable.java:130)
	at org.uqbar.project.wollok.interpreter.AbstractWollokCallable.lambda$0(AbstractWollokCallable.java:86)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.performOnStack(WollokInterpreter.java:199)
	at org.uqbar.project.wollok.interpreter.AbstractWollokCallable.call(AbstractWollokCallable.java:98)
	at org.uqbar.project.wollok.interpreter.core.WollokObject.call(WollokObject.java:119)
	at org.uqbar.project.wollok.interpreter.core.WollokObject.throwMessageNotUnderstood(WollokObject.java:146)
	at org.uqbar.project.wollok.interpreter.core.WollokObject.call(WollokObject.java:117)
	at org.uqbar.project.wollok.interpreter.operation.WollokDeclarativeNativeUnaryOperations._plus(WollokDeclarativeNativeUnaryOperations.java:112)
	at org.uqbar.project.wollok.interpreter.operation.WollokDeclarativeNativeUnaryOperations.plus(WollokDeclarativeNativeUnaryOperations.java:146)
	at org.uqbar.project.wollok.interpreter.operation.WollokDeclarativeNativeUnaryOperations.plusOperation(WollokDeclarativeNativeUnaryOperations.java:108)
	... 28 more
