### ISSUE TITLE
Static Diagram: Importing non existing class shows message error

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1142]
This is when you write intermediate code like 

```xtend
import model.ex
```

(Misses things like "ample.pepita")

So, it shows a message dialog. It should do nothing until user finishes.

**Comment by fdodino** [comment]
Full stack trace

```
java.lang.IllegalArgumentException: Segment cannot be null
	at org.eclipse.xtext.naming.QualifiedName.append(QualifiedName.java:257)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider$4.apply(WollokImportedNamespaceAwareLocalScopeProvider.java:130)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider$4.apply(WollokImportedNamespaceAwareLocalScopeProvider.java:1)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$5.next(Iterators.java:553)
	at com.google.common.collect.Iterators$5.next(Iterators.java:553)
	at com.google.common.collect.Iterators.addAll(Iterators.java:357)
	at com.google.common.collect.Iterables.addAll(Iterables.java:351)
	at com.google.common.collect.Sets.newLinkedHashSet(Sets.java:328)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.toSet(IterableExtensions.java:592)
	at org.uqbar.project.wollok.scoping.WollokGlobalScopeProvider.objectsFromLocalImport(WollokGlobalScopeProvider.java:121)
	at org.uqbar.project.wollok.scoping.WollokGlobalScopeProvider.doImportedObjects(WollokGlobalScopeProvider.java:106)
	at org.uqbar.project.wollok.scoping.WollokGlobalScopeProvider$3.apply(WollokGlobalScopeProvider.java:94)
	at org.uqbar.project.wollok.scoping.WollokGlobalScopeProvider$3.apply(WollokGlobalScopeProvider.java:1)
	at org.uqbar.project.wollok.scoping.cache.MapBasedWollokGlobalScopeCache.get(MapBasedWollokGlobalScopeCache.java:24)
	at org.uqbar.project.wollok.scoping.WollokGlobalScopeProvider.importedObjects(WollokGlobalScopeProvider.java:97)
	at org.uqbar.project.wollok.scoping.WollokGlobalScopeProvider.getScope(WollokGlobalScopeProvider.java:58)
	at org.eclipse.xtext.scoping.impl.DefaultGlobalScopeProvider.getScope(DefaultGlobalScopeProvider.java:61)
	at org.eclipse.xtext.scoping.impl.AbstractGlobalScopeProvider.getScope(AbstractGlobalScopeProvider.java:50)
	at org.uqbar.project.wollok.interpreter.WollokClassFinder.getClassScope(WollokClassFinder.java:245)
	at org.uqbar.project.wollok.interpreter.WollokClassFinder.searchClass(WollokClassFinder.java:112)
	at org.uqbar.project.wollok.interpreter.WollokClassFinder.getCachedClass(WollokClassFinder.java:82)
	at org.uqbar.project.wollok.ui.diagrams.classes.StaticDiagramView$3.apply(StaticDiagramView.java:419)
	at org.uqbar.project.wollok.ui.diagrams.classes.StaticDiagramView$3.apply(StaticDiagramView.java:1)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:643)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:554)
	at org.uqbar.project.wollok.ui.diagrams.classes.StaticDiagramView.getImportedClasses(StaticDiagramView.java:434)
	at org.uqbar.project.wollok.ui.diagrams.classes.StaticDiagramView$2$3.exec(StaticDiagramView.java:221)
	at org.uqbar.project.wollok.ui.diagrams.classes.StaticDiagramView$2$3.exec(StaticDiagramView.java:1)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:91)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:520)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:492)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:133)
	at org.uqbar.project.wollok.ui.diagrams.classes.StaticDiagramView$2.apply(StaticDiagramView.java:224)
	at org.uqbar.project.wollok.ui.diagrams.classes.StaticDiagramView$2.apply(StaticDiagramView.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.uqbar.project.wollok.ui.diagrams.classes.StaticDiagramView.createDiagramModel(StaticDiagramView.java:382)
	at org.uqbar.project.wollok.ui.diagrams.classes.StaticDiagramView$1.runInUIThread(StaticDiagramView.java:793)
	at org.eclipse.ui.progress.UIJob$1.run(UIJob.java:97)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4536)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4154)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```
