### ISSUE TITLE
Run all tests from a folder created inside src does nothing

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#1219]
I have a project with the following structure inside of the src folder:
3-objetos-y-mensajes (name of mumuki guide)
    tomYJerry (name of exercise)
      2 wlk files
      2 wtest files
   another folder for other exercise
      1 wlk file
      1 wtest file

When I select the src folder and choose to run all tests, this works, but when I select either of the folders inside of the src folder nothing happens and there is no stacktrace either. The test perspective shows up but it's empty and there is no other feedback.

**Comment by fdodino** [comment]
Yes, since multiple folder manipulation was developed after "Run all test" feature, I haven't tested it with different folder (is a missing functionality)

**Comment by fdodino** [comment]
I could reproduce it: in error log viewer it shows this stack trace

```bash
java.lang.NullPointerException
	at org.uqbar.project.wollok.ui.launch.shortcut.WollokLaunchShortcut.launch(WollokLaunchShortcut.java:55)
	at org.uqbar.project.wollok.ui.tests.shortcut.WollokTestLaunchShortcut.launch(WollokTestLaunchShortcut.java:38)
	at org.uqbar.project.wollok.ui.launch.shortcut.AbstractFileLaunchShortcut._doLaunch(AbstractFileLaunchShortcut.java:62)
	at org.uqbar.project.wollok.ui.launch.shortcut.AbstractFileLaunchShortcut.doLaunch(AbstractFileLaunchShortcut.java:80)
	at org.uqbar.project.wollok.ui.launch.shortcut.AbstractFileLaunchShortcut.launch(AbstractFileLaunchShortcut.java:30)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchShortcutExtension.launch(LaunchShortcutExtension.java:431)
	at org.eclipse.debug.internal.ui.actions.LaunchShortcutAction.runInternal(LaunchShortcutAction.java:85)
	at org.eclipse.debug.internal.ui.actions.LaunchShortcutAction.runWithEvent(LaunchShortcutAction.java:135)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1366)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1349)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1134)
	at org.eclipse.jface.action.ActionContributionItem.lambda$8(ActionContributionItem.java:1258)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)
```
