### ISSUE TITLE
ClassNotFound in editor for org.uqbar.project.wollok.typeSystem.xsemantics.ui.labeling.XSemanticsWollokTypeSystemLabelExtension

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#122]
I think that this really screws the editor

```
MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.emf.common.util.WrappedException: org.eclipse.core.runtime.CoreException: Plug-in org.uqbar.project.wollok.typeSystem.xsemantics.ui was unable to load class org.uqbar.project.wollok.typeSystem.xsemantics.ui.labeling.XSemanticsWollokTypeSystemLabelExtension.
    at org.eclipse.xtext.util.Exceptions.throwUncheckedException(Exceptions.java:23)
    at org.eclipse.xtext.ui.label.DeclarativeLabelProvider.handleTextError(DeclarativeLabelProvider.java:85)
    at org.eclipse.xtext.ui.label.DeclarativeLabelProvider$1.handle(DeclarativeLabelProvider.java:28)
    at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:295)
    at org.eclipse.xtext.ui.label.DeclarativeLabelProvider.doGetText(DeclarativeLabelProvider.java:49)
    at org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider.doGetText(DefaultEObjectLabelProvider.java:35)
    at org.eclipse.xtext.ui.label.AbstractLabelProvider.getStyledText(AbstractLabelProvider.java:119)
    at org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider._text(DefaultOutlineTreeProvider.java:247)
    at sun.reflect.GeneratedMethodAccessor42.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291)
    at org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider._createNode(DefaultOutlineTreeProvider.java:153)
    at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291)
    at org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider.createNode(DefaultOutlineTreeProvider.java:137)
    at org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider._createChildren(DefaultOutlineTreeProvider.java:118)
    at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291)
    at org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider.createChildren(DefaultOutlineTreeProvider.java:109)
    at org.eclipse.xtext.ui.editor.outline.impl.AbstractOutlineNode$1.process(AbstractOutlineNode.java:98)
    at org.eclipse.xtext.ui.editor.outline.impl.AbstractOutlineNode$1.process(AbstractOutlineNode.java:1)
    at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:36)
    at org.eclipse.xtext.ui.editor.outline.impl.AbstractOutlineNode$2.exec(AbstractOutlineNode.java:201)
    at org.eclipse.xtext.ui.editor.outline.impl.AbstractOutlineNode$2.exec(AbstractOutlineNode.java:1)
    at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:494)
    at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:465)
    at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:105)
    at org.eclipse.xtext.ui.editor.outline.impl.AbstractOutlineNode.readOnly(AbstractOutlineNode.java:194)
    at org.eclipse.xtext.ui.editor.outline.impl.AbstractOutlineNode.getChildren(AbstractOutlineNode.java:95)
    at org.eclipse.xtext.ui.editor.outline.actions.OutlineWithEditorLinker.findBestNode(OutlineWithEditorLinker.java:136)
    at org.eclipse.xtext.ui.editor.outline.actions.OutlineWithEditorLinker.findBestNode(OutlineWithEditorLinker.java:137)
    at org.eclipse.xtext.ui.editor.outline.actions.OutlineWithEditorLinker.findBestNode(OutlineWithEditorLinker.java:137)
    at org.eclipse.xtext.ui.editor.outline.actions.OutlineWithEditorLinker.findBestNode(OutlineWithEditorLinker.java:137)
    at org.eclipse.xtext.ui.editor.outline.actions.OutlineWithEditorLinker.selectInTreeView(OutlineWithEditorLinker.java:125)
    at org.eclipse.xtext.ui.editor.outline.actions.OutlineWithEditorLinker$TextListener.selectionChanged(OutlineWithEditorLinker.java:69)
    at org.eclipse.jface.text.TextViewer.firePostSelectionChanged(TextViewer.java:2750)
    at org.eclipse.jface.text.TextViewer.firePostSelectionChanged(TextViewer.java:2698)
    at org.eclipse.jface.text.TextViewer$5.run(TextViewer.java:2677)
    at org.eclipse.swt.widgets.Display.runTimers(Display.java:4174)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3660)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
    at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
Caused by: org.eclipse.core.runtime.CoreException: Plug-in org.uqbar.project.wollok.typeSystem.xsemantics.ui was unable to load class org.uqbar.project.wollok.typeSystem.xsemantics.ui.labeling.XSemanticsWollokTypeSystemLabelExtension.
    at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:194)
    at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:176)
    at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:905)
    at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:243)
    at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:55)
    at org.uqbar.project.wollok.ui.labeling.WollokDslLabelProvider.resolveLabelExtension(WollokDslLabelProvider.java:105)
    at org.uqbar.project.wollok.ui.labeling.WollokDslLabelProvider.concatResolvedType(WollokDslLabelProvider.java:76)
    at org.uqbar.project.wollok.ui.labeling.WollokDslLabelProvider.text(WollokDslLabelProvider.java:128)
    at sun.reflect.GeneratedMethodAccessor71.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.eclipse.xtext.util.PolymorphicDispatcher.invoke(PolymorphicDispatcher.java:291)
    ... 63 more
Caused by: java.lang.ClassNotFoundException: org.uqbar.project.wollok.typeSystem.xsemantics.ui.labeling.XSemanticsWollokTypeSystemLabelExtension cannot be found by org.uqbar.project.wollok.typeSystem.xsemantics.ui_1.0.0.qualifier
    at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
    at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
    at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:568)
    at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:174)
    ... 73 more
```

**Comment by fdodino** [comment]
I can't remember this happening to me.
@javierfernandes Did it happen to you?

**Comment by javierfernandes** [comment]
Yes. You need to be running with the typesystem plugins wich are not being
bundled with the wollok product. So this only happens to devs using all
wollok projects

**Comment by fdodino** [comment]
Ok, putting this into Backlog tasks, because @npasserini will assign priority to type system

**Comment by npasserini** [comment]
@tesonep Javier reported an issue regarding type system elements that were not being bundled, so I think we need your knowledge here. A few questions:
1) Is it still true that there are type system plugins that are not being bundled in the final product?
The error here is about xsemantics.

2) If that's true, how hard is it to limit the type system selection configuration to match installed type systems?

**Comment by javierfernandes** [comment]
My comment was almost 1 year ago (just by -11 days) :P
Maybe it is not reproducible anymore (?)

**Comment by tesonep** [comment]
1. I think this is only a problem of dependencies, the plugin is not well construct so the dependencies are not correctly resolved. I have to check it. 

2. I think is the same problem, the TS options are filled with the information in the extension point, but if the extension point points to a broken class, I have to fix it.

I will check it later. If none of you or me have fixed this, I think it is still open even it was a year old. Maybe we should wait and resolve it during the birthday of the issue 😃

**Comment by npasserini** [comment]
Yeah, I had saw the date, but sounds like something that could be still
happening. I think its better to check for it.

2017-08-10 9:18 GMT-03:00 Javier Fernandes <notifications@github.com>:

**Comment by npasserini** [comment]
Closing this issue as XSemantics type system has been removed from Wollok v1.7
