### ISSUE TITLE
NullPointerException in cache while adding / removing imports

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1232]
Steps to reproduce it (try it several times until it happens, because error is random)

1) Add a new file. Name it like you want. Lets say it is called "aves.wlk"
2) In that wlk file create a new wko. Name it like you want: lets call it "pepita".

```scala
// aves.wlk
object pepita {
}
```

3) Add another file. Lets call it "entrenador.wlk"

4) Add a test, program or wlk file. It doesn't matter whether it is one or another.
Add following import:

```xtend
import aves.*
import entrenador.*

test {
     pepita
}
```

5) Remove first import and add it again, over and over. Remove first import once again.
6) Write down "import aves.*" again. Try also "import aves.pepita"
7) Eventually you will get an error updating editor

```
Caused by: org.uqbar.project.wollok.interpreter.WollokRuntimeException: Error while resolving import 'entrenador'
	at org.uqbar.project.wollok.scoping.WollokGlobalScopeProvider.toResource(WollokGlobalScopeProvider.java:193)
	at org.uqbar.project.wollok.scoping.WollokGlobalScopeProvider.lambda$4(WollokGlobalScopeProvider.java:140)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:646)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:43)
	at com.google.common.collect.Iterators$5.hasNext(Iterators.java:542)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.exists(IteratorExtensions.java:256)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.exists(IterableExtensions.java:222)
	at org.uqbar.project.wollok.scoping.WollokScopeExtensions.containsImport(WollokScopeExtensions.java:27)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.lambda$1(WollokImportedNamespaceAwareLocalScopeProvider.java:115)
	at org.eclipse.xtext.xbase.lib.internal.BooleanFunctionDelegate.apply(BooleanFunctionDelegate.java:41)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:647)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.doGetImportedNamespaceResolvers(WollokImportedNamespaceAwareLocalScopeProvider.java:123)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.getImportedNamespaceResolvers(WollokImportedNamespaceAwareLocalScopeProvider.java:96)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.getResourceScope(WollokImportedNamespaceAwareLocalScopeProvider.java:69)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.getScope(WollokImportedNamespaceAwareLocalScopeProvider.java:60)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.getScope(WollokImportedNamespaceAwareLocalScopeProvider.java:58)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.getScope(WollokImportedNamespaceAwareLocalScopeProvider.java:58)
	at org.uqbar.project.wollok.scoping.WollokImportedNamespaceAwareLocalScopeProvider.getScope(WollokImportedNamespaceAwareLocalScopeProvider.java:58)
	at org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider.delegateGetScope(AbstractDeclarativeScopeProvider.java:72)
	at org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider.getScope(AbstractDeclarativeScopeProvider.java:104)
	at org.eclipse.xtext.linking.impl.DefaultLinkingService.getScope(DefaultLinkingService.java:59)
	at org.eclipse.xtext.linking.impl.DefaultLinkingService.getLinkedObjects(DefaultLinkingService.java:120)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:247)
	at org.eclipse.xtext.linking.lazy.LazyLinkingResource.getEObject(LazyLinkingResource.java:222)
	... 20 more
Caused by: java.lang.NullPointerException
	at org.uqbar.project.wollok.scoping.root.WollokRootLocator.calculateLevelsToRoot(WollokRootLocator.java:65)
	at org.uqbar.project.wollok.scoping.root.WollokRootLocator.levelsToRoot(WollokRootLocator.java:19)
	at org.uqbar.project.wollok.scoping.WollokGlobalScopeProvider.generateUri(WollokGlobalScopeProvider.java:207)
	at org.uqbar.project.wollok.scoping.WollokGlobalScopeProvider.toResource(WollokGlobalScopeProvider.java:183)
	... 55 more
```

**Comment by fdodino** [comment]
Apparently resourceSet is null somewhere 

```
def calculateLevelsToRoot(Resource resource) {
        ....
        value = doLevelsToRoot(parent, resource.resourceSet.URIConverter)
```

**Comment by fdodino** [comment]
Tried to debug, but many threads collide, and it is not easy to see why resourceSet of a certain resource  is null. Added this hacked workaround in WollokRootLocator:

```
	def calculateLevelsToRoot(Resource resource) {
		val uri = resource.URI
		
		if(uri.toString.contains("classpath:"))
			return 1
		
		val parent = uri.trimSegments(1)
		
		var value = cache.get(parent) as Integer
		value = null
		
		if(value === null){
			//value = doLevelsToRoot(parent, resource.resourceSet.URIConverter)
                        // begin hack
			val resourceSet = resource.resourceSet ?: new SynchronizedXtextResourceSet
			value = doLevelsToRoot(parent, resourceSet.URIConverter)
                       // end hack
			cache.put(parent, value)
		}
		
		value
	}
```

And errors went away, but sometimes import is not recognized and also autocompletion is lost.
I feel so close but I can't figure out...

**Comment by fdodino** [comment]
Same error as #1230

**Comment by fdodino** [comment]
[Uploading anim.gif...]
