### ISSUE TITLE
Unexpected runtime failure in super constructor call

### ISSUE THREAD

**Issue by mmatos** [uqbar-project/wollok#1288]
I have the following:
```
class UnidadArmada inherits Unidad {
	var arma
	
	constructor(unArma){
		arma = unArma
	}
..
}

class Arquero inherits UnidadArmada {
	constructor() = super(armeria.arco())
}

object armeria {
method arco() = new Arma(25)
}
```

This compiles, however doing new Arquero() fails on runtime. This is the walkback that appears in the REPL:

```
>>> new Arquero()
     Wollok VM Error in line  (1): new Arquero():
          Wollok VM Error in line  (62): armeria.arco():
               Wollok VM Error in line  (62): armeria:
                    Wollok VM Error in line  (11): object armeria {
	method arco() = new Arma(25)
	method espada() = new Arma(20)
	method mandoble() = new Arma(30)
}:
java.lang.UnsupportedOperationException: TODO: auto-generated method stub
	at org.uqbar.project.wollok.interpreter.context.MapBasedEvaluationContext.addGlobalReference(MapBasedEvaluationContext.java:77)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$13.apply(WollokInterpreterEvaluator.java:594)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$13.apply(WollokInterpreterEvaluator.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.createNamedObject(WollokInterpreterEvaluator.java:617)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:578)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:228)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:248)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:135)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:254)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:252)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:248)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:135)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluateTarget(WollokInterpreterEvaluator.java:774)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluateTarget(WollokInterpreterEvaluator.java:866)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:760)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:262)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:248)
	at org.uqbar.project.wollok.interpreter.AbstractWollokCallable.eval(AbstractWollokCallable.java:121)
	at org.uqbar.project.wollok.interpreter.AbstractWollokCallable$2.apply(AbstractWollokCallable.java:128)
	at org.uqbar.project.wollok.interpreter.AbstractWollokCallable$2.apply(AbstractWollokCallable.java:1)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:572)
	at java.util.AbstractList$Itr.next(Unknown Source)
	at java.util.AbstractCollection.toArray(Unknown Source)
	at com.google.common.collect.Iterables.toArray(Iterables.java:314)
	at org.eclipse.xtext.xbase.lib.Conversions.unwrapArray(Conversions.java:195)
	at org.uqbar.project.wollok.interpreter.core.WollokObject$5.apply(WollokObject.java:227)
	at org.uqbar.project.wollok.interpreter.core.WollokObject$5.apply(WollokObject.java:1)
	at org.uqbar.project.wollok.interpreter.threads.WThread.performOnStack(WThread.java:62)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.performOnStack(WollokInterpreter.java:323)
	at org.uqbar.project.wollok.interpreter.core.WollokObject.invokeOnContext(WollokObject.java:233)
	at org.uqbar.project.wollok.interpreter.core.WollokObject.evaluateConstructor(WollokObject.java:199)
	at org.uqbar.project.wollok.interpreter.core.WollokObject.invokeConstructor(WollokObject.java:189)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$12.apply(WollokInterpreterEvaluator.java:562)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$12.apply(WollokInterpreterEvaluator.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.newInstance(WollokInterpreterEvaluator.java:565)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:522)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:224)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:248)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:135)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:142)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:1)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:643)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:554)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evalAll(WollokInterpreterEvaluator.java:145)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:200)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:266)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:248)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:135)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator._evaluate(WollokLauncherInterpreterEvaluator.java:69)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:264)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.interpret(WollokInterpreter.java:172)
	at org.uqbar.project.wollok.launch.repl.WollokRepl.executeInput(WollokRepl.java:167)
	at org.uqbar.project.wollok.launch.repl.WollokRepl.startRepl(WollokRepl.java:93)
	at org.uqbar.project.wollok.launch.WollokLauncher.doSomething(WollokLauncher.java:87)
	at org.uqbar.project.wollok.launch.WollokChecker.launch(WollokChecker.java:101)
	at org.uqbar.project.wollok.launch.WollokChecker.doMain(WollokChecker.java:79)
	at org.uqbar.project.wollok.launch.WollokLauncher.main(WollokLauncher.java:39)
```

The error raised in the tests was different, with less details, simply WollokInterpreterException: Error evaluating line (...) new Arquero() and an irrelevant stacktrace.

I tried changing what I had for:

```
class Arquero inherits UnidadArmada {
	constructor() = super(new Arma(25))
}
```

which made it work, and this also worked, but of course it's not pretty:

```
class Arquero inherits UnidadArmada {
	constructor() = super(null){
		arma = armeria.arco()
	}
}
```

**Comment by fdodino** [comment]
I've got another strange situation 

https://github.com/pdp-mn-utn/tp-objetos-grupo-16/tree/Error_constructor/TPObjetos

VocalistaPopular inherits MusicoConRoles, 

```javascript
class MusicoConRoles inherits Musico {
	var rolInterpretador
	var rolCobrador
	constructor ( _habilidadBase, _rolInterpretador, _rolCobrador) = super ( _habilidadBase) {
		rolInterpretador = _rolInterpretador
		rolCobrador = _rolCobrador
	}
	override method internalInterpretaBien(cancion) = rolInterpretador.interpretaBien(cancion)
	override method cobra(presentacion) = rolCobrador.cobra(presentacion)
}

class VocalistaPopular inherits MusicoConRoles {
	override method habilidadExtra() = if (self.esSolista()) 0 else -20
}
```

So, it hasn't default constructors, because it inherits from another class which also inherits from another class.
but you can do
new VocalistaPopular()
It should not.

**Comment by fdodino** [comment]
@mmatos, Can you post Unidad class ? I wonder if it has one, several, or no constructor at all.

**Comment by fdodino** [comment]
Well,  the problem is a UnsupportedOperation in MapBasedEvaluationContext.
@tesonep , @npasserini  I changed this definition to

```xtend
	override addGlobalReference(String name, O value) {
		addReference(name, value)
		//throw new UnsupportedOperationException("TODO: auto-generated method stub")
	}
	
	override removeGlobalReference(String name) {
		values.remove(name)
		//throw new UnsupportedOperationException("TODO: auto-generated method stub")
	}
```

And everything began to work.
That's because you are calling a constructor, so WollokObject doesn't exist yet.
Passing all tests fine.
