### ISSUE TITLE
Not allow named and positional parameters together in constructor calls

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1374]
```Scala
object wollok {
	method perro() {
		return new Perro( nombre = "firulais", edad = 12, 23, 30, 50 )
	}
}

class Perro {
	var nombre
	var edad
	
	constructor(n, m, e) {
		nombre = n
		edad = e
	}
}
```

Throws
```Scala
>>> wollok.perro()
     Wollok VM Error in line  (1): wollok.perro():
               Wollok VM Error in line  (1): return new Perro( "asd", nombre = "firulais", edad = 12 ):
                    Wollok VM Error in line  (1): new Perro( "asd", nombre = "firulais", edad = 12 ):
java.lang.ClassCastException: org.uqbar.project.wollok.wollokDsl.impl.WStringLiteralImpl cannot be cast to org.uqbar.project.wollok.wollokDsl.WInitializer
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$11.apply(WollokInterpreterEvaluator.java:512)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$11.apply(WollokInterpreterEvaluator.java:1)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:643)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:554)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:519)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:224)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:253)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:139)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:498)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:238)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:253)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:139)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:146)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:1)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:643)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:554)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evalAll(WollokInterpreterEvaluator.java:149)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:695)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:218)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:253)
	at org.uqbar.project.wollok.interpreter.AbstractWollokCallable.eval(AbstractWollokCallable.java:123)
	at org.uqbar.project.wollok.interpreter.AbstractWollokCallable$1.apply(AbstractWollokCallable.java:78)
	at org.uqbar.project.wollok.interpreter.AbstractWollokCallable$1.apply(AbstractWollokCallable.java:1)
	at org.uqbar.project.wollok.interpreter.threads.WThread.performOnStack(WThread.java:62)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.performOnStack(WollokInterpreter.java:328)
	at org.uqbar.project.wollok.interpreter.AbstractWollokCallable.call(AbstractWollokCallable.java:91)
	at org.uqbar.project.wollok.interpreter.core.WollokObject.call(WollokObject.java:131)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:801)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:262)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:253)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:139)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:146)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:1)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:643)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:554)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evalAll(WollokInterpreterEvaluator.java:149)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:204)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:266)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:253)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:139)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator._evaluate(WollokLauncherInterpreterEvaluator.java:69)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:264)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.interpret(WollokInterpreter.java:171)
	at org.uqbar.project.wollok.launch.repl.WollokRepl.executeInput(WollokRepl.java:167)
	at org.uqbar.project.wollok.launch.repl.WollokRepl.startRepl(WollokRepl.java:93)
	at org.uqbar.project.wollok.launch.WollokLauncher.doSomething(WollokLauncher.java:87)
	at org.uqbar.project.wollok.launch.WollokChecker.launch(WollokChecker.java:129)
	at org.uqbar.project.wollok.launch.WollokChecker.doMain(WollokChecker.java:82)
	at org.uqbar.project.wollok.launch.WollokLauncher.main(WollokLauncher.java:39)
```

**Comment by fdodino** [comment]
Acá me quedé pensando @npasserini @PalumboN , poner una validación es fácil, pero no estoy seguro de que sea fácil hacerlo cambiando la gramática, ¿qué opinan?

**Comment by fdodino** [comment]
Bueno, lo que empecé a hacer es cambiar la gramática para que no acepte la mezcla (me falta para WKO y literales que heredan...) y  agregué la funcionalidad para que el parser detecte combinaciones de parámetros nombrados y valores.
[Uploading issue1374.png...]

**Comment by npasserini** [comment]
Ya que estás con eso, tal vez convenga revisar la llamada a this/super
dentro de un constructor, que no admite parámetros nombrados. Me parece que
debería.
No sé, en realidad es sutil, si complica no lo hagamos o pongámoslo como
nice to have.

2018-04-25 15:26 GMT-03:00 Fernando Dodino <notifications@github.com>:

**Comment by fdodino** [comment]
Ok, me fijo, lo agrego a esta lista de cosas que me encontré:

1) Verificar qué pasa con wko y objetos literales que hereden con named parameters (no hay tests)
2) WKO y literales que quieran mezclar named parameters, no lo debe permitir (generar tests)
3) Qué pasa cuando usás named parameters que no existan (que haya tests)
4) Ver si se puede atrapar un LinkerError cuando hacés el test de 
   new Perro(1, nombre = ...). Ayer se rompía todo antes de poder ejecutar el test porque no linkea.
5) Ya que estás con eso, tal vez convenga revisar la llamada a this/super
dentro de un constructor, que no admite parámetros nombrados. Me parece que
debería.

**Comment by npasserini** [comment]
Tiro dos ideas más, para pensar:
6) Otro detalle que vi, es que la gramática no linkea las variables que
aparecen en los initializers.
Tal vez podría ser útil aprovechar la lógica del linker, que ya debería
estar resuelta para los demás usos de variables.

7) Creo que sería bueno extraer en la gramática una entidad que fuera
WArgumentList, para que más adelante pueda ser compartida por métodos y
constructores (tanto explícitos como implícitos/automáticos/initialización
directa). Yo pienso que la forma de garantizar consistencia es que todo
admita parámetros nominales y posicionales.

2018-04-26 7:40 GMT-03:00 Fernando Dodino <notifications@github.com>:

**Comment by fdodino** [comment]
Pah! Para 7) qué onda esto:

```xtext
WConstructorCall:
	'new' classRef=[WClass|QualifiedName]'('
	argumentList=WArgumentList
	('with' mixins+=[WMixin])*
	')'
;

WArgumentList:
	{WArgumentList}	
		(=> initializers+=WInitializer (',' initializers+=WInitializer)*)?
		(values += WExpression (',' values += WExpression)*)?
;
```

¿Te cierra? Porque solo rompen 7 tests, je, tuve que cambiar algunas cositas pero los extension methods casi me salvaron. Después habría que hacer lo mismo para object literal y named object, y quedaría listo para el siguiente paso que son los feature call.

**Comment by npasserini** [comment]
Así escrito parece que un WArgumentList permitiría tanto initializers como
values, ¿es a propósito?

2018-04-26 14:25 GMT-03:00 Fernando Dodino <notifications@github.com>:

**Comment by npasserini** [comment]
En Ruby se puede, no sé si queremos tanta flexibilidad en Wollok, pero
tampoco es ilógico. Aunque creo que el orden debería ser al revés, como en
Ruby.
Interesante leer detalles en esta respuesta
<https://stackoverflow.com/questions/20633412/mixing-keyword-with-regular-arguments-in-ruby/20633975#20633975>
.

2018-04-26 14:56 GMT-03:00 Nicolas Passerini <npasserini@gmail.com>:

**Comment by fdodino** [comment]
Ahora sí me perdí.
Sí, mi idea es que tengas initializers **xor** values. Ponele que sea al revés el orden, da lo mismo.
Pero así no te permite intercambiar parámetros posicionales o nominales, es uno u otro.
Pero no entendí a qué apuntás con WArgumentList, si no es a aprovecharlo para WObjectLiteral, WNamedObject y WMemberFeatureCall después.
Me queda un test del type system en rojo (con el bendito pair.wlk.xt)

**Comment by fdodino** [comment]
Bueno, intenté dar vuelta values vs. initializers y el parser se vuelve loco.
Al revés ya lo tengo. Ahí lo subí. La gramática que quedó en el mail no es la que yo puse, porque me había equivocado, los paréntesis iban antes del "mixed with".

```xtend
WConstructorCall:
	'new' classRef=[WClass|QualifiedName]'('
	argumentList=WArgumentList
	')'
	('with' mixins+=[WMixin])*
;

WArgumentList:
	{WArgumentList}	
		(=> initializers+=WInitializer (',' initializers+=WInitializer)*)?
		(values += WExpression (',' values += WExpression)*)?
;
```

**Comment by npasserini** [comment]
Lo que yo digo es que así como está parece permitir las dos cosas. No me
jode el xor... pero no parece eso en la gramática.
Yo creo que debería ser

WArgumentList:
	{WArgumentList}	
		((=> initializers+=WInitializer (',' initializers+=WInitializer)*)|
		(values += WExpression (',' values += WExpression)*))?
;


O incluso

WArgumentList: WPositionalArgumentsList | WNamedArgumentsList
...

2018-04-26 15:26 GMT-03:00 Fernando Dodino <notifications@github.com>:

**Comment by fdodino** [comment]
Me gusta el WPositionalArgumentsList vs. WNamedArgumentsList.
