### ISSUE TITLE
Revisar posible error en el Outline

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1443]

**Comment by fdodino** [comment]
En Windows está ocurriendo

```
Caused by: java.lang.ClassCastException: org.eclipse.ui.part.MessagePage cannot be cast to org.eclipse.xtext.ui.editor.outline.impl.OutlinePage
	at org.uqbar.project.wollok.ui.WollokActivator$4.run(WollokActivator.java:174)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:162)
	at org.eclipse.ui.internal.UISynchronizer$3.run(UISynchronizer.java:154)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
```
