### ISSUE TITLE
Al cambiar la configuración para activar el Type System al hacer rebuild infiere todos los tipos como Any

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1444]

**Comment by fdodino** [comment]
Es necesario cerrar y abrir el IDE nuevamente para que el TS se active correctamente

**Comment by fdodino** [comment]
En Windows no lo pude reproducir. 
En Linux ocurre solo la primera vez, luego de grabar el archivo se genera ok.
No hay ningún error.

**Comment by fdodino** [comment]
Mmm... me parece que puede tener que ver con #1443, ya que el builder trata de refrescar el outline y tira error. Quizás si pasa eso el Builder queda con error y no se vuelve a ejecutar (recuerdo haber leído algo de eso).

**Comment by fdodino** [comment]
Confirmado en branch dev corriendo el producto, no se está ejecutando el builder y por eso al refrescar el Outline se visualiza todo como Any.

**Comment by fdodino** [comment]
Activé los println y está fallando al inicializar dinámicamente:

```
Builder - BUILD !!!!!!!!!!
Builder - build started. ProjectP/pepita
Builder - Listeners initialized true
Builder - Wollok files [org.eclipse.xtext.linking.lazy.LazyLinkingResource@3cb07812 uri='platform:/resource/pepita/src/example.wlk']
Checking if enabled - true
Builder - Initializing  org.uqbar.project.wollok.wollokDsl.impl.WFileImpl@44458fdb
java.lang.NullPointerException
	at org.uqbar.project.wollok.typesystem.constraints.typeRegistry.AnnotatedTypeRegistry.addMethodTypeDeclaration(AnnotatedTypeRegistry.java:55)
	at org.uqbar.project.wollok.typesystem.annotations.ExpectReturnType.operator_doubleArrow(ExpectReturnType.java:27)
	at org.uqbar.project.wollok.typesystem.annotations.WollokCoreTypeDeclarations$4.accept(WollokCoreTypeDeclarations.java:1114)
	at org.uqbar.project.wollok.typesystem.annotations.WollokCoreTypeDeclarations$4.accept(WollokCoreTypeDeclarations.java:1)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.uqbar.project.wollok.typesystem.annotations.WollokCoreTypeDeclarations.comparable(WollokCoreTypeDeclarations.java:1117)
	at org.uqbar.project.wollok.typesystem.annotations.WollokCoreTypeDeclarations.declarations(WollokCoreTypeDeclarations.java:1077)
	at org.uqbar.project.wollok.typesystem.annotations.TypeDeclarations$1.apply(TypeDeclarations.java:54)
	at org.uqbar.project.wollok.typesystem.annotations.TypeDeclarations$1.apply(TypeDeclarations.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.uqbar.project.wollok.typesystem.annotations.TypeDeclarations.addTypeDeclarations(TypeDeclarations.java:57)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintBasedTypeSystem$2.apply(ConstraintBasedTypeSystem.java:139)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintBasedTypeSystem$2.apply(ConstraintBasedTypeSystem.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintBasedTypeSystem.initialize(ConstraintBasedTypeSystem.java:142)
	at org.uqbar.project.wollok.typeSystem.ui.builder.WollokTypeSystemBuilderParticipant$2.apply(WollokTypeSystemBuilderParticipant.java:79)
	at org.uqbar.project.wollok.typeSystem.ui.builder.WollokTypeSystemBuilderParticipant$2.apply(WollokTypeSystemBuilderParticipant.java:1)
	at org.uqbar.project.wollok.typesystem.WollokTypeSystemActivator.ifEnabledFor(WollokTypeSystemActivator.java:173)
	at org.uqbar.project.wollok.typeSystem.ui.builder.WollokTypeSystemBuilderParticipant.build(WollokTypeSystemBuilderParticipant.java:115)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:161)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:69)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:291)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:319)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:155)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:403)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:551)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:529)
	at org.eclipse.core.internal.resources.Project.build(Project.java:112)
	at org.uqbar.project.wollok.utils.WEclipseUtils.fullBuild(WEclipseUtils.java:279)
	at org.uqbar.project.wollok.typeSystem.ui.preferences.TypeSystemPreferencePage$3.accept(TypeSystemPreferencePage.java:156)
	at org.uqbar.project.wollok.typeSystem.ui.preferences.TypeSystemPreferencePage$3.accept(TypeSystemPreferencePage.java:1)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.uqbar.project.wollok.typeSystem.ui.preferences.TypeSystemPreferencePage.rebuild(TypeSystemPreferencePage.java:159)
	at org.uqbar.project.wollok.typeSystem.ui.preferences.TypeSystemPreferencePage$1.run(TypeSystemPreferencePage.java:134)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Builder - refreshing views
Builder - generate issues for org.eclipse.xtext.linking.lazy.LazyLinkingResource@3cb07812 uri='platform:/resource/pepita/src/example.wlk'
Builder - refreshing type errors org.eclipse.xtext.linking.lazy.LazyLinkingResource@3cb07812 uri='platform:/resource/pepita/src/example.wlk'
Refresh errors in editor - calling partActivated
Part activated!!
    issues []

```

**Comment by npasserini** [comment]
¿Qué significa inicializar dinámicamente?
¿Eso pasa sólo con el product o lo puedo reproducir en desarrollo? ¿Cómo lo
reproduzco?

**Comment by fdodino** [comment]
Je, inicializar "dinámicamente" es cuando activás el Type System y forzás el rebuild.
Eso corre el builder y se está rompiendo en el initialize del TS.
Esto lo verifiqué corriendo el producto, entiendo que en modo desarrollo no pasa.

**Comment by fdodino** [comment]
Después de una larga serie de generaciones de producto encontré que el problema está acá:

```xtend
	def static lookUpMethod(Iterable<WMethodContainer> hierarchy, String message, List<?> params, boolean acceptsAbstract) {
		println("Lookup method")
		println("  accepts abstract " + acceptsAbstract)
		println("  message " + message)
		println("  hierarchy " + hierarchy)
		for (chunk : hierarchy) {
			val method = chunk.methods.findFirst[ (!it.abstract || acceptsAbstract) && matches(message, params)]
			if (method !== null)
				return method;
		}
		null
	}
```

Bah, no es que esté mal, pero la superclase de String no es exactamente Object, es un WClass pero no tiene el nombre puesto todavía, es WClass|wollok.lang#242.

Una vez que se cierra y se vuelve a abrir el IDE, todo empieza a funcionar de aquí en más (**esto significa que solo ocurre la primera vez que se quiere activar el TS, después funciona ok**, entonces quizás esté faltando mandar a cargar la cache antes de hacer el primer build del TS)

**Comment by npasserini** [comment]
Lo que no queda claro es por qué es necesario "cargar" la cache, si es una
cache debería automáticamente ir a buscar las cosas que no tiene, ¿no
funciona así?

**Comment by fdodino** [comment]
Todavía no estoy seguro qué hace. Pero sí que cuando le pedís el padre al WClass String, te devuelve un WClass que no dice Object:

```
Look up method === in org.uqbar.project.wollok.wollokDsl.impl.WClassImpl@562f5710 (name: String) - parent org.uqbar.project.wollok.wollokDsl.impl.WClassImpl@298b69a2 (eProxyURI: classpath:/wollok/lang.wlk#|242)
```

El problema lo tira acá:

```xtend
	def static WMethodDeclaration lookupMethod(WMethodContainer behavior, String message, List<?> params, boolean acceptsAbstract) {
		println("Look up method " + message + " in " + behavior + " - parent " + behavior.parent)
		lookUpMethod(behavior.linearizeHierarchy, message, params, acceptsAbstract)
	}
```

El parent de String no dice Object, sino la definición nro.242 de java.lang, lo que sigue es el log del lookupMethod interno, que divide cada elemento de la jerarquía en chunks. Y ahí se ve que ese elemento 242 no tiene métodos, por eso rompe cuando buscás un método definido en la superclase.

```
  --> chunk org.uqbar.project.wollok.wollokDsl.impl.WClassImpl@562f5710 (name: String) - [length, charAt, +, startsWith, endsWith, indexOf, lastIndexOf, toLowerCase, toUpperCase, trim, <, <=, >, >=, contains, isEmpty, equalsIgnoreCase, substring, substring, split, replace, toString, printString, toSmartString, ==, size, take, drop, words, capitalize]
  --> chunk org.uqbar.project.wollok.wollokDsl.impl.WClassImpl@298b69a2 (eProxyURI: classpath:/wollok/lang.wlk#|242) - []
java.lang.NullPointerException
	at org.uqbar.project.wollok.typesystem.constraints.typeRegistry.AnnotatedTypeRegistry.addMethodTypeDeclaration(AnnotatedTypeRegistry.java:55)
	at org.uqbar.project.wollok.typesystem.annotations.ExpectReturnType.operator_doubleArrow(ExpectReturnType.java:27)
	at org.uqbar.project.wollok.typesystem.annotations.WollokCoreTypeDeclarations$4.accept(WollokCoreTypeDeclarations.java:1114)
	at org.uqbar.project.wollok.typesystem.annotations.WollokCoreTypeDeclarations$4.accept(WollokCoreTypeDeclarations.java:1)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.uqbar.project.wollok.typesystem.annotations.WollokCoreTypeDeclarations.comparable(WollokCoreTypeDeclarations.java:1117)
	at org.uqbar.project.wollok.typesystem.annotations.WollokCoreTypeDeclarations.declarations(WollokCoreTypeDeclarations.java:1077)
	at org.uqbar.project.wollok.typesystem.annotations.TypeDeclarations$1.apply(TypeDeclarations.java:54)
	at org.uqbar.project.wollok.typesystem.annotations.TypeDeclarations$1.apply(TypeDeclarations.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.uqbar.project.wollok.typesystem.annotations.TypeDeclarations.addTypeDeclarations(TypeDeclarations.java:57)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintBasedTypeSystem$2.apply(ConstraintBasedTypeSystem.java:139)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintBasedTypeSystem$2.apply(ConstraintBasedTypeSystem.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintBasedTypeSystem.initialize(ConstraintBasedTypeSystem.java:142)
	at org.uqbar.project.wollok.typeSystem.ui.builder.WollokTypeSystemBuilderParticipant$2.apply(WollokTypeSystemBuilderParticipant.java:70)
	at org.uqbar.project.wollok.typeSystem.ui.builder.WollokTypeSystemBuilderParticipant$2.apply(WollokTypeSystemBuilderParticipant.java:1)
	at org.uqbar.project.wollok.typesystem.WollokTypeSystemActivator.ifEnabledFor(WollokTypeSystemActivator.java:169)
	at org.uqbar.project.wollok.typeSystem.ui.builder.WollokTypeSystemBuilderParticipant.build(WollokTypeSystemBuilderParticipant.java:90)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:161)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:69)
```

**Comment by fdodino** [comment]
El log completo lo subo acá. Es loco que al principio carga Object, y también Collection toma como padre a Object. Set y List heredan de Collection. Pero cuando recorre Boolean, el padre ya no es Object...

[B.txt](https://github.com/uqbar-project/wollok/files/2350889/B.txt)

Este en cambio es el que corre cuando cerrás el IDE y lo volvés a abrir. Anda perfecto.
[A.txt](https://github.com/uqbar-project/wollok/files/2350890/A.txt)

Yo voy a tratar de seguir con otras cosas porque esto me lleva infinito tiempo y solo pasa la primera vez, después podés hacer el cambio lo más bien. Algo del Scope puede estar jodiendo, pero es un escopetazo lo que estoy tirando...

**Comment by fdodino** [comment]
El commit tiene mal el mensaje, corresponde al issue #1477

**Comment by fdodino** [comment]
Cierro el issue porque está duplicado con el #1635
