### ISSUE TITLE
Open GL Problems

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1493]
In some machines Wollok Game doesn't work because of missing Open GL drivers. Giving this error:

```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: OpenGL is not supported by the video driver.
at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:229)
at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:174)
at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:138)
at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
Caused by: org.lwjgl.LWJGLException: Pixel format not accelerated
at org.lwjgl.opengl.WindowsPeerInfo.nChoosePixelFormat(Native Method)
at org.lwjgl.opengl.WindowsPeerInfo.choosePixelFormat(WindowsPeerInfo.java:52)
at org.lwjgl.opengl.WindowsDisplay.createWindow(WindowsDisplay.java:253)
at org.lwjgl.opengl.Display.createWindow(Display.java:306)
at org.lwjgl.opengl.Display.create(Display.java:848)
at org.lwjgl.opengl.Display.create(Display.java:757)
at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.createDisplayPixelFormat(LwjglGraphics.java:220)
... 3 more
```

**Comment by npasserini** [comment]
I tried a fix for this, which can be found in branch `fix-#1493-opengl-problems`, but it does not work. After installing a new product with this fix, we got another error:

```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: OpenGL 2.0 or higher with the FBO extension is required. OpenGL version: 1.1.0
at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.initiateGLInstances(LwjglGraphics.java:258)
at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:175)
at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:138)
at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

```

**Comment by npasserini** [comment]
Marking this as show stopper as WGame does not work if we don't fix this.

**Comment by Juancete** [comment]
I really don't know about it, but i found this:
https://stackoverflow.com/questions/32423629/opengl-2-0-or-higher-with-the-fbo-extension-is-required-libgdx-error

Seems to be an incompatibility between Java 1.8 and LibGDX. We have an older version of the framework. I don't know if upgrade it will bee a workaround.

**Comment by PalumboN** [comment]
Este año no vi este problema en ninguna máquina. @npasserini

**Comment by npasserini** [comment]
@51lv3str1 Lucas, te parece apuntarle a tener la versión sin libgdx para el próximo cuatri?
@PalumboN  qué opina?

**Comment by PalumboN** [comment]
:+1:

**Comment by faloi** [comment]
A un estudiante que usa Linux le pasó esto:

```Exception in thread "LWJGL Application" java.lang.NoClassDefFoundError: Could
not initialize class org.lwjgl.Sys
at org.lwjgl.opengl.Display.(Display.java:135)```

¿Estará relacionado?

**Comment by PalumboN** [comment]
@faloi no sé si está relacionado, pero parece que es un error de más bajo nivel que el de OpenGL. Eso le pasa al querer levantar cualquier juego? Podremos tener más info de la máquina en la que está corriendo?

**Comment by faloi** [comment]
El que sabe es @clombardi, él lo reportó.

**Comment by PalumboN** [comment]
Entiendo que ahora se tira este error por consola cuando los drivers no se bancan libgdx:
```
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: OpenGL 2.0 or higher with the FBO extension is required. OpenGL version: 1.1.0
```

Lo cual me parece bien. No sé si podemos evitar ese error.

@isaiaslafon si tenías ganas de jugar con esto está la versión nativa que hizo @51lv3str1 que entiendo que no tiene esta dependencia. Quizá se podría trabajar para reemplazar la versión actual por esa!

**Comment by asanzo** [comment]
Tengo 2 personas más con este problema. A ambes les estoy recomendando actualizar drivers, pero si no se puede, se quedan sin wollok game y sin poder hacer el TP integrador.
