### ISSUE TITLE
TS for Object Literals error

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#1523]

**Comment by fdodino** [comment]
```js
class Persona {

	var prueba = object {
		var a = 0
		method cenar() {
			return a
		}
	}
}
```

shows 

```
org.uqbar.project.wollok.typesystem.TypeSystemException: Type system: Missing type information for 0
	at org.uqbar.project.wollok.typesystem.constraints.variables.TypeVariablesRegistry.lambda$6(TypeVariablesRegistry.java:167)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.uqbar.project.wollok.typesystem.constraints.variables.TypeVariablesRegistry.tvar(TypeVariablesRegistry.java:170)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.AbstractInferenceStrategy.tvar(AbstractInferenceStrategy.java:110)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.GuessMinTypeVisitor._afterVisit(GuessMinTypeVisitor.java:77)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.GuessMinTypeVisitor.afterVisit(GuessMinTypeVisitor.java:158)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.visit(AbstractWollokVisitor.java:67)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor._visitChildren(AbstractWollokVisitor.java:174)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.GuessMinTypeVisitor.visitChildren(GuessMinTypeVisitor.java:237)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.visit(AbstractWollokVisitor.java:66)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.lambda$0(AbstractWollokVisitor.java:117)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.visitAll(AbstractWollokVisitor.java:119)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor._visitChildren(AbstractWollokVisitor.java:195)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.GuessMinTypeVisitor.visitChildren(GuessMinTypeVisitor.java:207)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.visit(AbstractWollokVisitor.java:66)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor._visitChildren(AbstractWollokVisitor.java:174)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.GuessMinTypeVisitor.visitChildren(GuessMinTypeVisitor.java:237)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.visit(AbstractWollokVisitor.java:66)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.lambda$0(AbstractWollokVisitor.java:117)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.visitAll(AbstractWollokVisitor.java:119)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor._visitChildren(AbstractWollokVisitor.java:191)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.GuessMinTypeVisitor.visitChildren(GuessMinTypeVisitor.java:243)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.visit(AbstractWollokVisitor.java:66)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.lambda$0(AbstractWollokVisitor.java:117)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.visitAll(AbstractWollokVisitor.java:119)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor._visitChildren(AbstractWollokVisitor.java:129)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.GuessMinTypeVisitor.visitChildren(GuessMinTypeVisitor.java:279)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.visit(AbstractWollokVisitor.java:66)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.GuessMinTypeFromMaxType.lambda$0(GuessMinTypeFromMaxType.java:32)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.GuessMinTypeFromMaxType.walkThrougProgram(GuessMinTypeFromMaxType.java:34)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.AbstractInferenceStrategy.run(AbstractInferenceStrategy.java:40)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintBasedTypeSystem.runStrategy(ConstraintBasedTypeSystem.java:214)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintBasedTypeSystem.lambda$4(ConstraintBasedTypeSystem.java:200)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.exists(IteratorExtensions.java:257)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.exists(IterableExtensions.java:222)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintBasedTypeSystem.runStage(ConstraintBasedTypeSystem.java:202)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintBasedTypeSystem.inferTypes(ConstraintBasedTypeSystem.java:179)
	at org.uqbar.project.wollok.typeSystem.ui.builder.WollokTypeSystemBuilderParticipant.lambda$1(WollokTypeSystemBuilderParticipant.java:67)
	at org.uqbar.project.wollok.typesystem.WollokTypeSystemActivator.ifEnabledFor(WollokTypeSystemActivator.java:163)
	at org.uqbar.project.wollok.typeSystem.ui.builder.WollokTypeSystemBuilderParticipant.build(WollokTypeSystemBuilderParticipant.java:77)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:161)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:69)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:291)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:267)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:161)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by PalumboN** [comment]
Buenas!

Acabo de subir una (primera) versión que agrega los ObjectLiterals al TS acá: https://github.com/uqbar-project/wollok/tree/ts-object-literal
La verdad que fue fácil porque ya estaba hecho, solo faltaba generar la variable correspondiente. Y la verdad que se la banca bastante, pueden ver [los tests](https://github.com/uqbar-project/wollok/compare/ts-object-literal?expand=1#diff-0a6ba633ba52f3435f9aec822a56626e).

Sin embargo, haciendo pruebas de polimorfismo, me encontré con esto que reporté en este issue (de ahí a que hay varias cosas comentadas): https://github.com/uqbar-project/wollok/issues/1526

Y tengo las siguientes dudas / comentarios / cosas para debatir:
1. No puede inferir los max types de un ObjectLiteral. Lo pueden ver en este test:
```scala
	// XPECT methodType at hacerHablarQueNuncaSeUsa(personalidad) -->  (Any) => Any	
	method hacerHablarQueNuncaSeUsa(personalidad) = personalidad.habla()
```
Eso es porque no tiene forma de encontrar ese tipo cuando se calcula el MaxType desde los mensajes que se mandan. Así que mi pregunta es si _deberíamos_ agregar los ObjectLiteralTypes al global (al igual que los NamedObjects y Classes) y si haciendo eso el TS puede encontrar ese tipo.

2. Me gusta que cuando sí lo puede calcular a partir de un uso que se hace del método lo muestra con el tipo estructural: `({ habla }) => String`. Lo malo es que eso se pierde cuando hay usos polimórficos: `((<object>|<object>)) => String`. Esto tiene algo que ver con el issue que comenté arriba.

3. Qué hacer en los casos que se tiene el mismo mensaje pero con distinto tipo (este caso no me vuelve muy feliz, en el sentido que no me gustaría verlo en clase, pero no se si restringir esos programas). Por ejemplo, tengo un objeto que `habla(): () => String` y otro con `habla(): () => Number` y se lo paso ambos al método `hacerHablar(personalidad)`.
Ahora está infiriendo algo como `((<object>|<object>)) => (String|Number)`. Pero no se si me pone muy feliz eso, porque a partir de ahí ya sea si llamo a `self.hacerHablar(cosaQueHablaConString)` o `self.hacerHablar(cosaQueHablaConNumero)` me infiere `(String|Number)` para ambos casos, cuando podría darse cuenta qué es lo que va a retornar.
Tal vez el problema está en que se está haciendo los tipos union de los parámetros y el return por separado, y no del _método_. Estaría más feliz con un tipo: `hacerHablar(personalidad) : (({ habla }) => String|({ habla }) => Number)`. Pero no se, me falta teoría.

Bueno, más allá de todo esto. Se ~re~ banca un uso _básico_ de ObjectLiteral. Aunque estaría bueno probarlo en un ejemplo concreto de clase.
No tire el PR por esas cositas que dije, pero pueden hacerlo si creen que es suficiente por ahora.

(Vengo leyendo la discusión en el mail épico sobre el futuro de OOP y me puso manija, de ahí que estoy tirando código desde Tailandia :) Abrazoosss )

**Comment by fdodino** [comment]
Saludos Thai !!!! Grande Nahue!

**Comment by npasserini** [comment]
Qué grande!
