### ISSUE TITLE
Errores en consola al correr tests

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1598]
Luego de mergear https://github.com/uqbar-project/wollok/pull/1577, al correr los tests de **WollokMultiInterpreterTest** aparecen varios errores en la consola (a pesar de que los tests dan verde):
```
org.uqbar.project.wollok.interpreter.WollokInterpreterException: Error evaluating line __synthetic0.wpgm:[1]: test "pepita vuela" {
	pepita.volar()
	assert.equals(90, pepita.energia())
}
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:275)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:140)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.lambda$0(WollokLauncherInterpreterEvaluator.java:94)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:643)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:554)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator._evaluate(WollokLauncherInterpreterEvaluator.java:100)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:257)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.interpret(WollokInterpreter.java:175)
	at org.uqbar.project.wollok.tests.multithread.WollokMultiInterpreterTest.testRunSameProgramTwice(WollokMultiInterpreterTest.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.uqbar.project.wollok.interpreter.WollokInterpreterException: Error evaluating line __synthetic0.wpgm:[2]: pepita.volar()
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:275)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:140)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.lambda$4(WollokLauncherInterpreterEvaluator.java:167)
	at org.uqbar.project.wollok.interpreter.threads.WThread.performOnStack(WThread.java:62)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.performOnStack(WollokInterpreter.java:341)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.lambda$3(WollokLauncherInterpreterEvaluator.java:169)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator._evaluate(WollokLauncherInterpreterEvaluator.java:171)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:261)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:263)
	... 32 more
Caused by: org.uqbar.project.wollok.interpreter.WollokInterpreterException: Error evaluating line __synthetic0.wpgm:[2]: pepita
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:275)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:140)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluateTarget(WollokInterpreterEvaluator.java:813)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluateTarget(WollokInterpreterEvaluator.java:905)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:784)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:255)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:263)
	... 42 more
Caused by: org.uqbar.project.wollok.interpreter.context.UnresolvableReference: Couldn't resolve reference to pepita
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:262)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:245)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:263)
	... 49 more
```

**Comment by fdodino** [comment]
Ja, justo hoy me pareció extraño que apareciera el stack trace en los tests.

**Comment by fdodino** [comment]
https://github.com/uqbar-project/wollok/blame/1fdf6ff0639fde50d7845e97f72fc7dc62741a53/org.uqbar.project.wollok/src/org/uqbar/project/wollok/interpreter/WollokInterpreter.xtend

Efectivamente fueron pruebas que hice para que apareciera en algún momento el stack trace pero creo que ahora está apareciendo un stack trace cuando no debe.
