### ISSUE TITLE
TS a veces se frula e infiere todo como ANY

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1635]
![image](https://user-images.githubusercontent.com/4098184/57184847-4ef0d080-6e98-11e9-959c-24cf68ceac42.png)

**Comment by fdodino** [comment]
Jaja, se "frula" yo lo conocía como "trula", y frula es otra cosa...

Les tiro otra:

**Comment by fdodino** [comment]
pucha con el enter

```js
object pepita {
	var energia = 100
	
	method energia() { 
		return energia
	}
	
	method esFuerte() { return energia > 50 }

	method volar(kms) {
		energia = energia - (kms + 10)
	}
	
	method comer(gramos) {
		energia = energia + 4 * gramos
	}
}
```

**Comment by PalumboN** [comment]
Esto pasa siempre que activás el TS, la primera vez. El error que loguea es:
```
!ENTRY org.apache.log4j 4 0 2019-07-18 05:42:30.556
!MESSAGE org.uqbar.project.wollok.typeSystem.ui.builder.WollokTypeSystemBuilderParticipant  - Type inference failed

!STACK 0
java.lang.IllegalArgumentException: Type system configuration error. You are trying to add a type annotation for method !=/1 in type Date, which does not exist
	at org.uqbar.project.wollok.typesystem.constraints.typeRegistry.AnnotatedTypeRegistry.lambda$0(AnnotatedTypeRegistry.java:72)
	at org.uqbar.project.wollok.utils.XtendExtensions.lambda$0(XtendExtensions.java:42)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.uqbar.project.wollok.typesystem.constraints.typeRegistry.AnnotatedTypeRegistry.addMethodTypeDeclaration(AnnotatedTypeRegistry.java:75)
	at org.uqbar.project.wollok.typesystem.annotations.ExpectReturnType.operator_doubleArrow(ExpectReturnType.java:27)
	at org.uqbar.project.wollok.typesystem.annotations.WollokCoreTypeDeclarations.lambda$0(WollokCoreTypeDeclarations.java:75)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.uqbar.project.wollok.typesystem.annotations.WollokCoreTypeDeclarations.declarations(WollokCoreTypeDeclarations.java:169)
	at org.uqbar.project.wollok.typesystem.annotations.TypeDeclarations.lambda$4(TypeDeclarations.java:59)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.uqbar.project.wollok.typesystem.annotations.TypeDeclarations.lambda$0(TypeDeclarations.java:61)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.uqbar.project.wollok.typesystem.annotations.TypeDeclarations.addTypeDeclarations(TypeDeclarations.java:66)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintBasedTypeSystem.lambda$1(ConstraintBasedTypeSystem.java:140)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintBasedTypeSystem.initialize(ConstraintBasedTypeSystem.java:150)
	at org.uqbar.project.wollok.typeSystem.ui.builder.WollokTypeSystemBuilderParticipant.lambda$1(WollokTypeSystemBuilderParticipant.java:80)
	at org.uqbar.project.wollok.typesystem.WollokTypeSystemActivator.ifEnabledFor(WollokTypeSystemActivator.java:163)
	at org.uqbar.project.wollok.typeSystem.ui.builder.WollokTypeSystemBuilderParticipant.build(WollokTypeSystemBuilderParticipant.java:95)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:161)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:69)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:291)
	at org.eclipse.xtext.builder.impl.XtextBuilder.fullBuild(XtextBuilder.java:319)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:155)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:403)
	at org.eclipse.core.internal.resources.Project$1.run(Project.java:551)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Project.internalBuild(Project.java:529)
	at org.eclipse.core.internal.resources.Project.build(Project.java:112)
	at org.uqbar.project.wollok.utils.WEclipseUtils.fullBuild(WEclipseUtils.java:273)
	at org.uqbar.project.wollok.typeSystem.ui.preferences.TypeSystemPreferencePage.lambda$1(TypeSystemPreferencePage.java:149)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.uqbar.project.wollok.typeSystem.ui.preferences.TypeSystemPreferencePage.rebuild(TypeSystemPreferencePage.java:151)
	at org.uqbar.project.wollok.typeSystem.ui.preferences.TypeSystemPreferencePage$1.run(TypeSystemPreferencePage.java:132)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by PalumboN** [comment]
Pasa que Object se vuelve un proxy y devuelve `methods() = []`, es porque quedan resources desactualizados.

**Comment by fdodino** [comment]
Ah, ayer estuve mirando el #1444 que está duplicado, yo cierro el otro issue, fijate que hice pruebas y no terminaba de entender qué pasaba, para mí el tema es que el TS se activa antes que el refresh de los resources, pero lo loco es que solo pasa la primera vez.

Si después de muchas vueltas no le encontramos una solución, un workaround puede ser detectar que es esa primera vez y mostrar un mensaje en las preferencias cuando lo seteás la primera vez avisando que tenés que reiniciar. Mejor avisar.

**Comment by PalumboN** [comment]
Check https://github.com/uqbar-project/wollok/issues/1724

**Comment by fdodino** [comment]
Te paso a comentar:

```xtend
	def calculateImports(Resource context) {
		val importsCache = new OnChangeEvictingCache().getOrCreate(context)
		var result = importsCache.get("ImportsInResource")
		
		if (result === null) {
			val rootObject = context.contents.get(0)
			cache.invalidateDependencies(rootObject.eResource.URI) 
			result = (rootObject.allImports.map[importedNamespace] + rootObject.allFQNImports).toSet
			importsCache.set("ImportsInResource", result)
		}
		result
	}
```

esto lo usan los imports para rebuildear las dependencias cuando cambia algún recurso, creo que es lo que habría que hacer... otra cosa loadAllResources quizás debería usar la cache? :grey_question: 
:thinking:
