### ISSUE TITLE
[TS] ConcurrentModificationException

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1641]
El TS a veces falla al reportar errores con `ConcurrentModificationException`. Esto está matando al `WollokTypeSystemBuilderParticipant`? Eso sería grave no?

```
[Worker-34] FATAL org.uqbar.project.wollok.typeSystem.ui.builder.WollokTypeSystemBuilderParticipant  - Type inference failed
java.util.ConcurrentModificationException
	at java.util.HashMap$Values.forEach(HashMap.java:984)
	at org.uqbar.project.wollok.typesystem.constraints.variables.TypeVariablesRegistry.fullReport(TypeVariablesRegistry.java:267)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintBasedTypeSystem.inferTypes(ConstraintBasedTypeSystem.java:186)
	at org.uqbar.project.wollok.typeSystem.ui.builder.WollokTypeSystemBuilderParticipant.lambda$0(WollokTypeSystemBuilderParticipant.java:85)
	at org.uqbar.project.wollok.typesystem.WollokTypeSystemActivator.ifEnabledFor(WollokTypeSystemActivator.java:163)
	at org.uqbar.project.wollok.typeSystem.ui.builder.WollokTypeSystemBuilderParticipant.build(WollokTypeSystemBuilderParticipant.java:102)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:161)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:69)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:291)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:267)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:161)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by npasserini** [comment]
Esto tendría una solución en https://github.com/uqbar-project/wollok/commit/0a8a2d852408a55bb6a41a743b68aeda2fdfdbd6#diff-2581472d729071a315816cd6c8229067R164
