### ISSUE TITLE
No se puede tipar #-1

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#1665]
Este método: `	method mordisco() { peso = (peso * 0.8 - 1).max(0) }`
Da este error: 

```
!STACK 0
org.uqbar.project.wollok.typesystem.TypeSystemException: Type system: Missing type information for #-1 = #-1 * 0.8 - 1.max(0)
	at org.uqbar.project.wollok.typesystem.constraints.variables.TypeVariablesRegistry.lambda$8(TypeVariablesRegistry.java:180)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.uqbar.project.wollok.typesystem.constraints.variables.TypeVariablesRegistry.tvar(TypeVariablesRegistry.java:183)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.AbstractInferenceStrategy.tvar(AbstractInferenceStrategy.java:110)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.GuessMinTypeVisitor._afterVisit(GuessMinTypeVisitor.java:77)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.GuessMinTypeVisitor.afterVisit(GuessMinTypeVisitor.java:158)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.visit(AbstractWollokVisitor.java:67)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.lambda$0(AbstractWollokVisitor.java:117)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.visitAll(AbstractWollokVisitor.java:119)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor._visitChildren(AbstractWollokVisitor.java:256)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.GuessMinTypeVisitor.visitChildren(GuessMinTypeVisitor.java:177)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.visit(AbstractWollokVisitor.java:66)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor._visitChildren(AbstractWollokVisitor.java:232)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.GuessMinTypeVisitor.visitChildren(GuessMinTypeVisitor.java:246)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.visit(AbstractWollokVisitor.java:66)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.lambda$0(AbstractWollokVisitor.java:117)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.visitAll(AbstractWollokVisitor.java:119)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor._visitChildren(AbstractWollokVisitor.java:199)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.GuessMinTypeVisitor.visitChildren(GuessMinTypeVisitor.java:198)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.visit(AbstractWollokVisitor.java:66)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.lambda$0(AbstractWollokVisitor.java:117)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.visitAll(AbstractWollokVisitor.java:119)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor._visitChildren(AbstractWollokVisitor.java:129)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.GuessMinTypeVisitor.visitChildren(GuessMinTypeVisitor.java:279)
	at org.uqbar.project.wollok.visitors.AbstractWollokVisitor.visit(AbstractWollokVisitor.java:66)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.GuessMinTypeFromMaxType.lambda$0(GuessMinTypeFromMaxType.java:32)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.GuessMinTypeFromMaxType.walkThrougProgram(GuessMinTypeFromMaxType.java:34)
	at org.uqbar.project.wollok.typesystem.constraints.strategies.AbstractInferenceStrategy.run(AbstractInferenceStrategy.java:40)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintBasedTypeSystem.runStrategy(ConstraintBasedTypeSystem.java:213)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintBasedTypeSystem.lambda$4(ConstraintBasedTypeSystem.java:199)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.exists(IteratorExtensions.java:257)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.exists(IterableExtensions.java:222)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintBasedTypeSystem.runStage(ConstraintBasedTypeSystem.java:201)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintBasedTypeSystem.inferTypes(ConstraintBasedTypeSystem.java:178)
	at org.uqbar.project.wollok.typeSystem.ui.builder.WollokTypeSystemBuilderParticipant.lambda$1(WollokTypeSystemBuilderParticipant.java:85)
	at org.uqbar.project.wollok.typesystem.WollokTypeSystemActivator.ifEnabledFor(WollokTypeSystemActivator.java:163)
	at org.uqbar.project.wollok.typeSystem.ui.builder.WollokTypeSystemBuilderParticipant.build(WollokTypeSystemBuilderParticipant.java:95)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant$DeferredBuilderParticipant.build(RegistryBuilderParticipant.java:161)
	at org.eclipse.xtext.builder.impl.RegistryBuilderParticipant.build(RegistryBuilderParticipant.java:69)
	at org.eclipse.xtext.builder.impl.XtextBuilder.doBuild(XtextBuilder.java:291)
	at org.eclipse.xtext.builder.impl.XtextBuilder.incrementalBuild(XtextBuilder.java:267)
	at org.eclipse.xtext.builder.impl.XtextBuilder.build(XtextBuilder.java:161)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:735)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:301)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:304)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:360)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:383)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:144)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:235)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)


```

**Comment by npasserini** [comment]
Estuvimos probando esto con @Guusy  y nos anda lo más bien.
¿@PalumboN vos recordás algún detalle extra de cómo reproducirlo?
¿Lo cerramos?

**Comment by PalumboN** [comment]
Yo creo que nunca tuve este error. Lo cierro.
