### ISSUE TITLE
Método game.sound(archivo) no funciona

### ISSUE THREAD

**Issue by leodelgadodev** [uqbar-project/wollok#1669]
Al intentar enviar este mensaje desde un programa .wpgm con un archivo mp3 (que está en la carpeta Assets) me muestra el siguiente error:

`org.uqbar.project.wollok.interpreter.core.WollokProgramExceptionWrapper
	at org.uqbar.project.wollok.ui.utils.XTendUtilExtensions.wrapNativeException(XTendUtilExtensions.java:381)
	at org.uqbar.project.wollok.ui.utils.XTendUtilExtensions.invokeConvertingArgs(XTendUtilExtensions.java:351)
	at org.uqbar.project.wollok.interpreter.AbstractWollokCallable._invokeNative(AbstractWollokCallable.java:109)
	at org.uqbar.project.wollok.interpreter.AbstractWollokCallable.invokeNative(AbstractWollokCallable.java:184)
	at org.uqbar.project.wollok.interpreter.AbstractWollokCallable$1.apply(AbstractWollokCallable.java:70)
	at org.uqbar.project.wollok.interpreter.AbstractWollokCallable$1.apply(AbstractWollokCallable.java:1)
	at org.uqbar.project.wollok.interpreter.threads.WThread.performOnStack(WThread.java:62)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.performOnStack(WollokInterpreter.java:362)
	at org.uqbar.project.wollok.interpreter.AbstractWollokCallable.call(AbstractWollokCallable.java:91)
	at org.uqbar.project.wollok.interpreter.core.WollokObject.call(WollokObject.java:133)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:829)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:267)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:281)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:145)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:152)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:1)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:643)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:554)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evalAll(WollokInterpreterEvaluator.java:155)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:217)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:271)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:281)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:145)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator._evaluate(WollokLauncherInterpreterEvaluator.java:71)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:269)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.interpret(WollokInterpreter.java:178)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.interpret(WollokInterpreter.java:104)
	at org.uqbar.project.wollok.launch.WollokLauncher.doSomething(WollokLauncher.java:78)
	at org.uqbar.project.wollok.launch.WollokChecker.launch(WollokChecker.java:158)
	at org.uqbar.project.wollok.launch.WollokChecker.doMain(WollokChecker.java:90)
	at org.uqbar.project.wollok.launch.WollokLauncher.main(WollokLauncher.java:43)
wollok.lang.Exception: null
   at wollok.game.game.sound(audioFile) (classpath:/wollok/game.wlk:206)`

![error sound wollok](https://user-images.githubusercontent.com/46352908/59967474-b1f9fd80-9500-11e9-814e-1f1139edf889.png)

**Comment by fdodino** [comment]
hola @leodelgadodev !
Gracias por reportar el issue. Para facilitar la corrección, te pedimos si podés pasarnos el link de tu repositorio.
Saludos y suerte
Fernando

**Comment by npasserini** [comment]
Creo que toma los archivos de sonido de src en lugar de assets.
(Este comentario vale tanto para corregir el problema como para buscar work
arounds hasta que la solución esté.)

**Comment by fdodino** [comment]
Ah, me suena a que `assets` no está definido como carpeta fuente (source folder), como dice la documentación en [el sitio oficial de Wollok](www.wollok.org):

![image](https://user-images.githubusercontent.com/4549002/60096649-de439300-9727-11e9-9071-8dcb694f498f.png)

Igualmente, lo que podemos hacer es avisar que el archivo no fue encontrado y sugerir que revise el nombre del archivo y si la carpeta en la que está fue definida como carpeta fuente, pero no fallar, como cuando no encuentra una imagen. Podría salir el warning por consola.

**Comment by npasserini** [comment]
No creo que sea eso Fer, tendría que rechequear, pero me parece que vi
proyectos donde las imágenes funcionaban bien y los sonidos no.

**Comment by fdodino** [comment]
ahí vi el problema: el tema pasa cuando la aplicación todavía no está iniciada (funciona con los listeners)

**Comment by fdodino** [comment]
@npasserini @PalumboN, no es fácil de solucionar el inconveniente. El problema es que el objeto Gdx global no está inicializado, eso  te obliga a esperar a que esté corriendo LWjdxApplication. Por el momento lo que se me ocurre es al menos avisar que lo deberías poner en un listener:

![image](https://app.gitkraken.com/api/glo/boards/5c8bfc72c68810000ff6fd50/attachments/5d1aa6b3d1606700156f0555)

(el mensaje falta parametrizarlo y mejorarlo).

A futuro creo que habría que repensar si queremos tener un sonido de fondo: backgroundSound, y que lo buffereemos hasta que la app levante. Pero como hay varios temas dando vueltas con Wollok Game lo itero hasta acá.

**Comment by npasserini** [comment]
Con saber que eso no vale es suficiente, después se puede buscar
workarounds dentro de lo que la herramienta permite.
Una sola pregunta simple si intercambio en ese ejemplo las líneas que
tienen sound y start, ¿igual no anda?

**Comment by fdodino** [comment]
Sí, probé hacerlo al revés pero no funciona.
Otra cosa que hay que ver es que si lo corrés en el REPL no encuentra el archivo, supongo que tiene que ver con que el Launcher no agrega la source folder assets. Habría que crear otro issue para eso.
