### ISSUE TITLE
Desvincular los constructores del Type System

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1905]
Actualmente la única conexión que hay es al inferir `Pair`.

- Ver de evitar atarse al constructor y usar los parámetros nombrados.
- Si no es así, evitar la inferencia de los tipos paramétricos y ver más adelante.

#### El tema es eliminar los constructores :skull:

**Comment by PalumboN** [comment]
Related https://github.com/uqbar-project/wollok-language/issues/35

**Comment by fdodino** [comment]
Agrego el log que está tirando por abajo el Type system en Wollok Ingalls:

```bash
java.lang.IllegalArgumentException: ConstraintBasedTypeSystem: tried to get a class type for wollok.lang.Pair but this is not possible because it is a generic type and must be instantiated before being used
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintBasedTypeSystem.classType(ConstraintBasedTypeSystem.java:264)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintGenerator._addGlobals(ConstraintGenerator.java:141)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintGenerator.addGlobals(ConstraintGenerator.java:582)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintGenerator.lambda$0(ConstraintGenerator.java:130)
```

**Comment by fdodino** [comment]
El commit no tiene nada que ver, me confundí el número con el anterior, el 1904.

**Comment by PalumboN** [comment]
@fdodino Jaaja ok. Cuándo tira ese error?? Cómo lo veo?

**Comment by fdodino** [comment]
Levanté la aplicación desde dev directamente... y si ves el Stack Trace de la consola de Eclipse RCP (la original) me aparece...
