### ISSUE TITLE
Errores silenciosos del TS

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#1907]
Al levantar la aplicación desde Eclipse, en la consola original se tiran los siguientes errores (detectado en Wollok Ingalls):

```bash
java.lang.IllegalArgumentException: ConstraintBasedTypeSystem: tried to get a class type for wollok.lang.Pair but this is not possible because it is a generic type and must be instantiated before being used
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintBasedTypeSystem.classType(ConstraintBasedTypeSystem.java:264)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintGenerator._addGlobals(ConstraintGenerator.java:141)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintGenerator.addGlobals(ConstraintGenerator.java:582)
	at org.uqbar.project.wollok.typesystem.constraints.ConstraintGenerator.lambda$0(ConstraintGenerator.java:130)
```

Esto sucede porque intenta agregar todas las clases como instancia de un tipo pero algunas tienen un tipo genérico. 

- Habría que detectar esos casos y evitarlos, ya que actualmente se agregan en la declaración del core y solamente las clases del core permiten ser genéricas.

**Comment by PalumboN** [comment]
Esto podría estar relacionado con https://github.com/uqbar-project/wollok/issues/1635
