### ISSUE TITLE
Confusing error message on forgotten return

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#198]
Given this program:

	val o = object {
		method getterWithoutReturn() { 10 }
	}
	
	val v1 = 10 * o.getterWithoutReturn()

The program has an error, it tries to multiply the result of evaluating o.getterWithoutReturn() but it does not return any value. (In fact, such a method does not even make sense.)

The real bug in Wollok is that this error is not correctly handled:

	Caused by: org.uqbar.project.wollok.interpreter.MessageNotUnderstood: 10 does not understand *
	at org.uqbar.project.wollok.ui.utils.XTendUtilExtensions.invoke(XTendUtilExtensions.java:236)
	at org.uqbar.project.wollok.interpreter.nativeobj.AbstractWollokWrapperNativeObject.doesNotUnderstand(AbstractWollokWrapperNativeObject.java:31)
	at org.uqbar.project.wollok.interpreter.nativeobj.AbstractWollokDeclarativeNativeObject.call(AbstractWollokDeclarativeNativeObject.java:38)
	at org.uqbar.project.wollok.interpreter.operation.WollokDeclarativeNativeBasicOperations._multiply(WollokDeclarativeNativeBasicOperations.java:249)
	at org.uqbar.project.wollok.interpreter.operation.WollokDeclarativeNativeBasicOperations.multiply(WollokDeclarativeNativeBasicOperations.java:780)
	at org.uqbar.project.wollok.interpreter.operation.WollokDeclarativeNativeBasicOperations.multiplyOperation(WollokDeclarativeNativeBasicOperations.java:234)
	... 29 more

**Comment by npasserini** [comment]
Similar error on expression: equipos.max([e| e.getEnergiaGenerada()])

Produces also a wrong error message.
    Caused by: java.lang.ClassCastException: org.uqbar.project.wollok.interpreter.stack.VoidObject cannot be cast to java.lang.Comparable

**Comment by javierfernandes** [comment]
Part of this problem is now detected statically by the checker.
If you override a method which was returning a value, then your new method must also return a value.
And same idea for the opposite case.

See #214

Still I think we could do more than that. So I'll let this opened.
I think that it's a really annoying problem that happens too often.

**Comment by javierfernandes** [comment]
This also can be workaround by #234 which checks getters for returning a value.
It uses the "getXxxx" naming convention, so it won't apply for all cases, but well, it should address some at least.

**Comment by javierfernandes** [comment]
I think that this new issue will completely solve this one and complement with the other I have mentioned.

#305

Please check that and we will close this one upon solving #305

**Comment by javierfernandes** [comment]
We now have a new check that analyzes the body of the method and warns you if it thinks you forgot the return statement

#309 

I think this the best we can do to tackle the problem in a static way. At least without a type system.
