### ISSUE TITLE
collection.any() produces an error if the collection has only one element.

### ISSUE THREAD

**Issue by npasserini** [uqbar-project/wollok#199]
Caused by: org.uqbar.project.wollok.interpreter.WollokInterpreterException: Error evaluating line file:/home/npasserini/checkout/uqbar/wollok/wollok-tests/src/wollok/examples/monstersinc/modelo.wlk:[15]: puertas.any()
		at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:203)
		at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:131)
		at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$2.apply(WollokInterpreterEvaluator.java:146)
		at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$2.apply(WollokInterpreterEvaluator.java:1)
		at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
		at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:572)
		at java.util.AbstractList$Itr.next(AbstractList.java:358)
		at java.util.AbstractCollection.toArray(AbstractCollection.java:196)
		at com.google.common.collect.Iterables.toArray(Iterables.java:314)
		at org.eclipse.xtext.xbase.lib.Conversions.unwrapArray(Conversions.java:96)
		at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evalEach(WollokInterpreterEvaluator.java:149)
		at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:690)
		at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:157)
		at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:191)
		... 69 more
	Caused by: java.lang.IllegalArgumentException: bound must be positive
		at java.util.Random.nextInt(Random.java:388)

**Comment by javierfernandes** [comment]
fixed in hotfixes
