### ISSUE TITLE
[debugger] StackTrace view explodes while debugging

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#30]
When it pauses in a breakpoint then trying to inspect the stack shows an error
![screen shot 2015-04-02 at 11 38 48](https://cloud.githubusercontent.com/assets/4428120/6966131/f6911dd2-d92c-11e4-95e8-b3e5d224ef4c.png)

And the following error in console

```
!ENTRY org.eclipse.core.jobs 4 2 2015-04-02 11:37:05.858
!MESSAGE An internal error occurred during: "child count update".
!STACK 0
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy44.getStackFrames(Unknown Source)
	at org.uqbar.project.wollok.ui.debugger.WollokDebugTarget.getStackFrames(WollokDebugTarget.java:224)
	at org.uqbar.project.wollok.ui.debugger.model.WollokThread.getStackFrames(WollokThread.java:33)
	at org.eclipse.debug.internal.ui.model.elements.ThreadContentProvider.getChildCount(ThreadContentProvider.java:29)
	at org.eclipse.debug.internal.ui.model.elements.ElementContentProvider.retrieveChildCount(ElementContentProvider.java:118)
	at org.eclipse.debug.internal.ui.model.elements.ElementContentProvider$2.run(ElementContentProvider.java:67)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786)
	at java.io.ObjectOutputStream.reset(ObjectOutputStream.java:503)
	at net.sf.lipermi.handler.ConnectionHandler.sendMessage(ConnectionHandler.java:182)
	at net.sf.lipermi.handler.ConnectionHandler.remoteInvocation(ConnectionHandler.java:207)
	at net.sf.lipermi.handler.CallProxy.invoke(CallProxy.java:58)
	... 7 more

!ENTRY org.eclipse.core.jobs 4 2 2015-04-02 11:38:41.915
!MESSAGE An internal error occurred during: "Check Debug Command".
!STACK 0
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy44.getStackFrames(Unknown Source)
	at org.uqbar.project.wollok.ui.debugger.WollokDebugTarget.getStackFrames(WollokDebugTarget.java:224)
	at org.uqbar.project.wollok.ui.debugger.model.WollokThread.getStackFrames(WollokThread.java:33)
	at org.uqbar.project.wollok.ui.debugger.model.WollokThread.canStepReturn(WollokThread.java:138)
	at org.eclipse.debug.internal.core.commands.StepReturnCommand.isSteppable(StepReturnCommand.java:27)
	at org.eclipse.debug.internal.core.commands.StepCommand.isExecutable(StepCommand.java:46)
	at org.eclipse.debug.core.commands.AbstractDebugCommand$UpdateJob.run(AbstractDebugCommand.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786)
	at java.io.ObjectOutputStream.reset(ObjectOutputStream.java:503)
	at net.sf.lipermi.handler.ConnectionHandler.sendMessage(ConnectionHandler.java:182)
	at net.sf.lipermi.handler.ConnectionHandler.remoteInvocation(ConnectionHandler.java:207)
	at net.sf.lipermi.handler.CallProxy.invoke(CallProxy.java:58)
	... 8 more
```

**Comment by javierfernandes** [comment]
Also fixed by

https://github.com/uqbar-project/wollok/commit/0681e19b3a23b2812dea2e9fe27bcc77f347a621
