### ISSUE TITLE
Model all AssertionException as wollok exceptions instead of java/xtend

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#430]
When a program fails by throwing one of such exceptions the strack trace is something like this (a lot of details of the interpreter)

``` java
org.uqbar.project.wollok.interpreter.WollokInterpreterException: Error evaluating line file:/Users/jfernandes/dev/data/repo/wollok-dev/wollok-tests/src/wollok/examples/monstersinc/workspace.wpgm:[17]: /**
 *
 */
program monstersInc {

    // 1)
    val sullivan = new AsustadorNato(25, 200)
    val puertaConNinio4 = new Puerta(new Ninio(4))

    assert.equals(1251, sullivan.entrarAPuerta(puertaConNinio4))


    // 2)
    val mike = new AsustadorPerseverante(20)
    mike.mejora(new EstudiarMateria("Sustos 2", 50))
    mike.mejora(new EjercitarEnSimulador(2))

    assert.that(70 == mike.puntosDeTerror())

    val piyamada = new Piyamada()
    piyamada.agregarNinio(new Ninio(2))
    piyamada.agregarNinio(new Ninio(3))
    piyamada.agregarNinio(new Ninio(4))

    val puertaConPiyamada = new Puerta(piyamada)

    val energiaMike = mike.entrarAPuerta(puertaConPiyamada)

    this.println(mike)
    assert.that(75 == energiaMike)   // 70/2 + 70/3 + 70/4 = 75


    // 3)
    val equipo = new Equipo(sullivan, new AsistenteNormal())
    equipo.visitar(new Puerta(new Adolescente()))

    assert.equals(90.0, sullivan.getNivelMotivacion())
    assert.that(0 == equipo.getEnergiaGenerada())


    // 4)

    val emp = monstersInc
    emp.agregarEquipo(equipo)
    emp.agregarPuerta(puertaConNinio4)
    emp.diaLaboral()
    assert.equals(1125.0, equipo.getEnergiaGenerada())

    // 5)
    assert.that(equipo == emp.equipoMasAsustador())

    val equipoCapo = object {
        method getEnergiaGenerada() { return 90000.0 }
    }
    emp.agregarEquipo(equipoCapo)

    assert.that(equipoCapo == emp.equipoMasAsustador())

}
    at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:237)
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:132)
    at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator._evaluate(WollokLauncherInterpreterEvaluator.java:63)
    at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:184)
    at org.uqbar.project.wollok.interpreter.WollokInterpreter.interpret(WollokInterpreter.java:141)
    at org.uqbar.project.wollok.interpreter.WollokInterpreter.interpret(WollokInterpreter.java:117)
    at org.uqbar.project.wollok.launch.WollokLauncher.doSomething(WollokLauncher.java:39)
    at org.uqbar.project.wollok.launch.WollokChecker.doMain(WollokChecker.java:82)
    at org.uqbar.project.wollok.launch.WollokLauncher.main(WollokLauncher.java:29)
Caused by: org.uqbar.project.wollok.interpreter.WollokInterpreterException: Error evaluating line file:/Users/jfernandes/dev/data/repo/wollok-dev/wollok-tests/src/wollok/examples/monstersinc/workspace.wpgm:[23]: assert.equals(1251, sullivan.entrarAPuerta(puertaConNinio4))
    at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:237)
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:132)
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:138)
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:1)
    at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:626)
    at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:534)
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evalAll(WollokInterpreterEvaluator.java:141)
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:184)
    at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:186)
    at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:225)
    ... 8 more
Caused by: wollok.lib.ValueWasNotEqualsException: Expected [1251] but found [1250]
    at wollok.lib.AssertionException.valueNotWasEquals(AssertionException.java:61)
    at wollok.lib.AssertObject.assertEquals(AssertObject.java:64)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.uqbar.project.wollok.ui.utils.XTendUtilExtensions.invokeConvertingArgs(XTendUtilExtensions.java:350)
    at org.uqbar.project.wollok.interpreter.nativeobj.AbstractWollokDeclarativeNativeObject.call(AbstractWollokDeclarativeNativeObject.java:77)
    at org.uqbar.project.wollok.interpreter.AbstractWollokCallable._invokeNative(AbstractWollokCallable.java:129)
    at org.uqbar.project.wollok.interpreter.AbstractWollokCallable.invokeNative(AbstractWollokCallable.java:187)
    at org.uqbar.project.wollok.interpreter.AbstractWollokCallable$1.apply(AbstractWollokCallable.java:73)
    at org.uqbar.project.wollok.interpreter.WollokInterpreter.performOnStack(WollokInterpreter.java:184)
    at org.uqbar.project.wollok.interpreter.AbstractWollokCallable.call(AbstractWollokCallable.java:95)
    at org.uqbar.project.wollok.interpreter.core.WollokObject.call(WollokObject.java:110)
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._call(WollokInterpreterEvaluator.java:791)
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.call(WollokInterpreterEvaluator.java:898)
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.perform(WollokInterpreterEvaluator.java:787)
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:767)
    at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:182)
    at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:225)
    ... 17 more

```

It should be something like

``` java
Exception wollok.lib.ValueWasNotEqualsException: Expected [1251] but found [1250]
    at monstersinc.workspace.wpgm:[23]
    at monstersinc.workspace.wpgm:[3]
```

**Comment by fdodino** [comment]
I think this was already achieved, but I have to test in my notebook.

**Comment by fdodino** [comment]
This program

 ```scala
program monstersInc {

    // 1)
    assert.equals(4, 5)
}
```

produces this output now::

```
wollok.lib.AssertionException: Expected [4] but found [5]
	at wollok.lib.assert.equals(expected,actual) [/lib.wlk:88]
	at  [/program.wpgm:4]
```
