### ISSUE TITLE
WDK is not being generated with all the dependencies

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#472]
Causes many ClassNotFound exceptions

Example:

```java
    [main] ERROR roject.wollok.launch.WollokLauncher  - org/eclipse/xtext/xbase/jvmmodel/IJvmModelAssociations
java.lang.NoClassDefFoundError: org/eclipse/xtext/xbase/jvmmodel/IJvmModelAssociations
 at org.uqbar.project.wollok.WollokDslRuntimeModule.configure(WollokDslRuntimeModule.java:42)
 at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:223)
 at com.google.inject.spi.Elements.getElements(Elements.java:101)
 at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:133)
 at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:103)
 at com.google.inject.Guice.createInjector(Guice.java:95)
 at com.google.inject.Guice.createInjector(Guice.java:72)
 at com.google.inject.Guice.createInjector(Guice.java:62)
 at org.uqbar.project.wollok.launch.setup.WollokLauncherSetup.createInjector(WollokLauncherSetup.java:32)
 at org.uqbar.project.wollok.WollokDslStandaloneSetupGenerated.createInjectorAndDoEMFRegistration(WollokDslStandaloneSetupGenerated.java:22)
 at org.uqbar.project.wollok.launch.WollokChecker.doMain(WollokChecker.java:78)
 at org.uqbar.project.wollok.launch.WollokLauncher.main(WollokLauncher.java:29)
Caused by: java.lang.ClassNotFoundException: org.eclipse.xtext.xbase.jvmmodel.IJvmModelAssociations
 at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
 at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
 ... 12 more
```

And this one

```java

Exception in thread "main" java.lang.NoClassDefFoundError: net/sf/lipermi/handler/CallHandler
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: net.sf.lipermi.handler.CallHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
```

**Comment by javierfernandes** [comment]
Looking at the "allDeps" folder where the dependencies plugin stores all the dependencies I've seen that it creates some folders for deps from other projects

```
-rw-r--r--   1 jfernandes  staff   3.9M Dec 11 10:14 org.uqbar.project.wollok-1.3.0.201512111252.jar
drwxr-xr-x   3 jfernandes  staff   102B Dec 11 10:14 org.uqbar.project.wollok.game-1.3.0.201512111252-target/
-rw-r--r--   1 jfernandes  staff   5.8M Dec 11 10:14 org.uqbar.project.wollok.game-1.3.0.201512111252.jar
drwxr-xr-x   5 jfernandes  staff   170B Dec 11 10:14 org.uqbar.project.wollok.launch-1.3.0.qualifier-lib/
-rw-r--r--   1 jfernandes  staff   221K Dec 11 10:14 org.uqbar.project.wollok.lib-1.3.0.201512111252.jar
-rw-r--r--   1 jfernandes  staff    32K Dec 11 10:14 org.w3c.css.sac-1.3.1.v200903091627.jar
-rw-r--r--   1 jfernandes  staff    13K Dec 11 10:14 org.w3c.dom.events-3.0.0.draft20060413_v201105210656.jar
-rw-r--r--   1 jfernandes  staff    24K Dec 11 10:14 org.w3c.dom.smil-1.0.1.v200903091627.jar
-rw-r--r--   1 jfernandes  staff    86K Dec 11 10:14 org.w3c.dom.svg-1.1.0.v201011041433.jar
```

Seems like we are not copying those

**Comment by javierfernandes** [comment]
Fixed in dev.
Will be deployed in a while here http://download.uqbar.org/wollok/sdk/dev/


@flbulgarelli

**Comment by flbulgarelli** [comment]
Thanks!
