### ISSUE TITLE
WGame forces you to have the flying_bird image for new games

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#483]
If I create a new game and try to run it will fail with this error

```java
2015-12-14 11:17:29.845 java[5240:5204625] 11:17:29.845 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: flying_bird.png
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:140)
	at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setupDisplay(LwjglGraphics.java:155)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:138)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: flying_bird.png (Internal)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:137)
	at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:223)
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:137)
	... 3 more

```

**Comment by javierfernandes** [comment]
Same for speech.png

```java
2015-12-14 11:19:20.895 java[5246:5205230] 11:19:20.895 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: assets/speech.png
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:140)
	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:100)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:92)
	at org.uqbar.project.wollok.game.gameboard.Window.<init>(Window.java:17)
	at org.uqbar.project.wollok.game.gameboard.GameboardRendering.create(GameboardRendering.java:28)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: assets/speech.png (Internal)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:137)
	at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:223)
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:137)
	... 7 more

```
