### ISSUE TITLE
Stackoverflow in the editor error if a WKO refers to itself in some method

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#491]
Example
```xtend
object wakman {

    method  blah() {
            other.blah(wakman)
    }

}
```

stacktrace
```java
	at org.uqbar.project.wollok.visitors.AbstractVisitor.visitAll(AbstractVisitor.java:70)
	at org.uqbar.project.wollok.visitors.AbstractVisitor._visit(AbstractVisitor.java:119)
	at org.uqbar.project.wollok.visitors.VariableAssignmentsVisitor.visit(VariableAssignmentsVisitor.java:130)
	at org.uqbar.project.wollok.visitors.VariableAssignmentsVisitor.doVisit(VariableAssignmentsVisitor.java:89)
	at org.uqbar.project.wollok.visitors.AbstractVisitor.lambda$0(AbstractVisitor.java:68)
	at org.uqbar.project.wollok.visitors.AbstractVisitor$$Lambda$48/1557939151.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.uqbar.project.wollok.visitors.AbstractVisitor.visitAll(AbstractVisitor.java:70)
	at org.uqbar.project.wollok.visitors.AbstractVisitor._visit(AbstractVisitor.java:196)
	at org.uqbar.project.wollok.visitors.VariableAssignmentsVisitor.visit(VariableAssignmentsVisitor.java:112)
	at org.uqbar.project.wollok.visitors.VariableAssignmentsVisitor.doVisit(VariableAssignmentsVisitor.java:89)
	at org.uqbar.project.wollok.visitors.AbstractVisitor._visit(AbstractVisitor.java:156)
	at org.uqbar.project.wollok.visitors.VariableAssignmentsVisitor.visit(VariableAssignmentsVisitor.java:181)
	at org.uqbar.project.wollok.visitors.VariableAssignmentsVisitor.doVisit(VariableAssignmentsVisitor.java:89)
```

**Comment by fdodino** [comment]
Solved in 1.5 version. Now it shows a message: "Don't use the name within the object. Use 'self' instead."
Closing this issue.
:smile:
