### ISSUE TITLE
Must show a predefined image if it cannot found one

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#493]
Currently if your object returns a file name that doesn't exists, it breaks with the following exception

```java
2015-12-14 19:33:54.583 java[2012:93020] 19:33:54.583 WARNING:  140: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load file: wakman-png
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:140)
	at com.badlogic.gdx.graphics.TextureData$Factory.loadFromFile(TextureData.java:98)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:100)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:92)
	at org.uqbar.project.wollok.game.Image.getTexture(Image.java:41)
	at org.uqbar.project.wollok.game.gameboard.Window.drawIn(Window.java:40)
	at org.uqbar.project.wollok.game.gameboard.Window.draw(Window.java:36)
	at org.uqbar.project.wollok.game.VisualComponent.drawMe(VisualComponent.java:84)
	at org.uqbar.project.wollok.game.VisualComponent.lambda$1(VisualComponent.java:76)
	at org.uqbar.project.wollok.game.VisualComponent$$Lambda$106/827097574.apply(Unknown Source)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.uqbar.project.wollok.game.VisualComponent.draw(VisualComponent.java:80)
	at org.uqbar.project.wollok.game.gameboard.Gameboard.lambda$1(Gameboard.java:98)
	at org.uqbar.project.wollok.game.gameboard.Gameboard$$Lambda$105/2106227545.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.uqbar.project.wollok.game.gameboard.Gameboard.draw(Gameboard.java:100)
	at org.uqbar.project.wollok.game.gameboard.GameboardRendering.render(GameboardRendering.java:35)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: File not found: wakman-png (Internal)
	at com.badlogic.gdx.files.FileHandle.read(FileHandle.java:137)
	at com.badlogic.gdx.files.FileHandle.readBytes(FileHandle.java:223)
	at com.badlogic.gdx.graphics.Pixmap.<init>(Pixmap.java:137)
	... 18 more

```

Instead it should show a predefined image like a red arrow

**Comment by PalumboN** [comment]
Why a _red arrow_?

I was thinking in the wollok icon
![icon_64x64](https://cloud.githubusercontent.com/assets/4098184/12047551/0e6458c0-aeac-11e5-8958-06c17d7f6505.png)
Because it's circular form, like objects!

And we could log something like "Image not found, please check the path." if there is one, too.
Or maybe the object itself can say that :eyes:

**Comment by javierfernandes** [comment]
Ok. I was thinking on a red "cross" to let it clear that thee was an error.
But the w icon should do it. Maybe adding a "no image" overlay text
