### ISSUE TITLE
Navigate to super from object implementing an abstract mixin method fails

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#575]
Example:

```xtend
mixin Iterable {
	method iterator()
	method reverseIterator()	
}

object abc mixed with Iterable {
	override method iterator() {}
	override method reverseIterator () {}
}
```

Doesn't go up and the first eclipse logs this
```java
java.lang.NullPointerException
	at org.eclipse.emf.ecore.util.EcoreUtil.getURI(EcoreUtil.java:3048)
	at org.uqbar.project.wollok.ui.editor.annotations.WOverrideRulerAction.lambda$1(WOverrideRulerAction.java:158)
	at org.uqbar.project.wollok.ui.editor.annotations.WOverrideRulerAction$$Lambda$119/445239365.exec(Unknown Source)
	at org.eclipse.xtext.resource.OutdatedStateManager.exec(OutdatedStateManager.java:121)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.internalReadOnly(XtextDocument.java:520)
	at org.eclipse.xtext.ui.editor.model.XtextDocument$XtextDocumentLocker.readOnly(XtextDocument.java:492)
	at org.eclipse.xtext.ui.editor.model.XtextDocument.readOnly(XtextDocument.java:133)
	at org.uqbar.project.wollok.ui.editor.annotations.WOverrideRulerAction.runInternal(WOverrideRulerAction.java:163)
	at org.uqbar.project.wollok.ui.editor.annotations.WOverrideRulerAction.run(WOverrideRulerAction.java:141)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.ui.texteditor.AbstractTextEditor$14.triggerAction(AbstractTextEditor.java:3082)
	at org.eclipse.ui.texteditor.AbstractTextEditor$14.access$1(AbstractTextEditor.java:3065)
	at org.eclipse.ui.texteditor.AbstractTextEditor$15.run(AbstractTextEditor.java:3096)
	at org.eclipse.swt.widgets.Display.runTimers(Display.java:4204)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3689)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
```

**Comment by javierfernandes** [comment]
Fixed !
