### ISSUE TITLE
Boolean expressions errors are not properly handled

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#698]
See the following: 

``` wollok
program abc {
    if (4) {
        console.println('foo')
    }
       //....
}
```

This program is obviously wrong, but the editor accepts it. And then it fails on runtime with a ver difficult to understand error: 

```
org.uqbar.project.wollok.interpreter.WollokInterpreterException: Error evaluating line file:/home/franco/Downloads/wollok-linux.gtk.x86_64%20(1)/workspace/mi-proyecto/src/program.wpgm:[15]: program abc {
        if (4) {
            console.println('foo')
        }
}
    at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:248)
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:132)
    at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator._evaluate(WollokLauncherInterpreterEvaluator.java:68)
    at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:212)
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
    at org.uqbar.project.wollok.interpreter.WollokInterpreter.interpret(WollokInterpreter.java:149)
    at org.uqbar.project.wollok.interpreter.WollokInterpreter.interpret(WollokInterpreter.java:123)
    at org.uqbar.project.wollok.launch.WollokLauncher.doSomething(WollokLauncher.java:43)
    at org.uqbar.project.wollok.launch.WollokChecker.doMain(WollokChecker.java:83)
    at org.uqbar.project.wollok.launch.WollokLauncher.main(WollokLauncher.java:31)
Caused by: org.uqbar.project.wollok.interpreter.WollokInterpreterException: Error evaluating line file:/home/franco/Downloads/wollok-linux.gtk.x86_64%20(1)/workspace/mi-proyecto/src/program.wpgm:[16]: if (4) {
            console.println('foo')
        }
    at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:248)
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:132)
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:139)
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:1)
    at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:627)
    at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:536)
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evalAll(WollokInterpreterEvaluator.java:142)
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:187)
    at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:214)
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
    at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:236)
    ... 9 more
Caused by: org.uqbar.project.wollok.interpreter.WollokInterpreterException: Expression in 'if' must evaluate to a boolean. Instead got: 4 (org.uqbar.project.wollok.interpreter.core.WollokObject)Error evaluating line file:/home/franco/Downloads/wollok-linux.gtk.x86_64%20(1)/workspace/mi-proyecto/src/program.wpgm:[16]: if (4) {
            console.println('foo')
        }
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:250)
    at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:178)
    at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
    at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:236)
    ... 19 more
```

There are here two problems: 
1. The editor does not check boolean expression that can be checked on edit-time 
2. The error message is not clear at all on runtime - this is important because not all non boolean expression can be checked on edit-time

It may not look like a big issue, but there are a lot of cases where it is really easy for the newcomer to face such errors. E.g.:

``` ẁollok
object pepita {
    var energia = 0
    method estaViva() {
        return energia = 0 ;
    }
}
```

I would expect something like `type error: object $object is not a boolean`

**Comment by fdodino** [comment]
Fixed somehow.
I tried both examples and Wollok checker complains 

if (4) ==> Expecting a boolean
return energia = 0 ==> Cannot return an assignment
