### ISSUE TITLE
Exceptions thrown with self.error are different from those thrown by throw

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#710]
See the following code: 

```
program abc {
	throw new Exception("foo");
	console.println(null + "hello")
}	
```

It nicely produces: 

```
wollok.lang.Exception: foo
	at  [/program.wpgm:23]
```

But, the following: 

```wollok
program abc {
	self.error("foo")
	console.println(null + "hello")
}
```

Produces a strange error: 

```
org.uqbar.project.wollok.interpreter.WollokInterpreterException: Error evaluating line file:/home/franco/Downloads/wollok-linux.gtk.x86_64%20(1)/workspace/mi-proyecto/src/program.wpgm:[22]: program abc {
	self.error("foo")
	console.println(null + "hello")
}
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:248)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:132)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator._evaluate(WollokLauncherInterpreterEvaluator.java:68)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:212)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.interpret(WollokInterpreter.java:149)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.interpret(WollokInterpreter.java:123)
	at org.uqbar.project.wollok.launch.WollokLauncher.doSomething(WollokLauncher.java:43)
	at org.uqbar.project.wollok.launch.WollokChecker.doMain(WollokChecker.java:83)
	at org.uqbar.project.wollok.launch.WollokLauncher.main(WollokLauncher.java:31)
Caused by: org.uqbar.project.wollok.interpreter.WollokInterpreterException: Error evaluating line file:/home/franco/Downloads/wollok-linux.gtk.x86_64%20(1)/workspace/mi-proyecto/src/program.wpgm:[23]: self.error("foo")
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:248)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:132)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:139)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:1)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:627)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:536)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evalAll(WollokInterpreterEvaluator.java:142)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:187)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:214)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:236)
	... 9 more
Caused by: org.uqbar.project.wollok.interpreter.WollokInterpreterException: Error evaluating line file:/home/franco/Downloads/wollok-linux.gtk.x86_64%20(1)/workspace/mi-proyecto/src/program.wpgm:[23]: self
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:248)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:132)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluateTarget(WollokInterpreterEvaluator.java:824)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluateTarget(WollokInterpreterEvaluator.java:914)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:789)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:210)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:236)
	... 19 more
Caused by: java.lang.UnsupportedOperationException: Cannot use this in a program's code !
	at org.uqbar.project.wollok.interpreter.core.WollokNativeLobby.getThisObject(WollokNativeLobby.java:43)
	at org.uqbar.project.wollok.interpreter.core.WollokNativeLobby.getThisObject(WollokNativeLobby.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:783)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:192)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:236)
	... 26 more
```

It seems that it `self.error` is not expected to be thrown by user code. Can we provide a method that actually woks from user code, or fix it?

Related to #694

**Comment by fdodino** [comment]
Mmm.... wollok.wlk has this implementation

```
method error(message) {
	throw new Exception(message)
}
```

Error is generated here
in WollokNativeLobby

``` java
	override getThisObject() { throw new UnsupportedOperationException("Cannot use this in a program's code !")}
```

**Comment by fdodino** [comment]
Oh, now I understand.
It is a find & replace problem. 
@flbulgarelli What about "Cannot use reference self in a program's code!"

**Comment by PalumboN** [comment]
Ok changing deprecated error message, but the issue continue, not?

I think the problem is because that error is thrown on execution, when it should be on compilation.

For me, this program
```XTend
program abc {
    self.error("foo")
    console.println(null + "hello")
}
```
should not be valid.

**Comment by flbulgarelli** [comment]
The problem is that the `error` message should be behave like a shortcut to throw exceptions given a messages - which is useful when teaching about exceptions and presenting them for the first time, before you introduce the concept of exception classes.  `error` should throw a `wollok.lang.Exception`, but it throws an internal exception  which is meaningless for student.

**Comment by PalumboN** [comment]
We can use another object for that, like `error.throw(message)`. So we can throw exceptions from a program or REPL avoiding the self reference error.

**Comment by flbulgarelli** [comment]
> We can use another object for that, like error.throw(message). So we can throw exceptions from a program or REPL avoiding the self reference error.

Works for me @PalumboN

**Comment by fdodino** [comment]
Ok, I misunderstood the problem.

**Comment by fdodino** [comment]
Finally Franco and I realized that Rasta was right:
- message should be updated "this" -> "self"
- also an error object could help (is it necessary, what do you think @npasserini  @javierfernandes ?)
- but, main problem is that you can't use "self" word outside a class/object definition. Don't know what about test, but using "self" in REPL and program should make Wollok not compile.

**Comment by matifreyre** [comment]
The error object looks like a nice, clean solution to me... we have an
assert WKO, a console WKO, a wgame/game WKO, all of which are of a similar
approach.

**Comment by javierfernandes** [comment]
Yeap, programs used to have "this".
But as programs are not coded in a wollok class extending object it was
kind of confusing.

Also people started to move from programs to REPL and tests, so we removed
support for things like this.println() and this.assert() in programs.
They were moved to WKO of the SDK (console and assert).

Currently for sure the static checker should be giving feedback about
writting "self" in both programs and REPL.

Eventually if we want behavior on programs and REPL, the best would be to
model them as wollok classes.

**Comment by javierfernandes** [comment]
I'm not sure about and "error" object.
What does it mean ?
Why someone would like to do self.error() in a REPL ?

And AFAIK programs are not used anymore for teaching.

At the end self.error(..) is just a shortcut for new Exception()
You can do that directly.

I find it weird to have an "error" object that is not an error and that
only has a single method to throw errors.

"Enlightme" with some other responsibilities it would have

**Comment by matifreyre** [comment]
On Wed, Jun 29, 2016 at 4:33 PM, javierfernandes <notifications@github.com>
wrote:

> I'm not sure about and "error" object.
> What does it mean ?
> Why someone would like to do self.error() in a REPL ?
>

I wasn't thinking about REPL, but about programs. I usually don't use it,
but why would you not be able to break a program? You may want to do it in
very simple demonstration programs, even if it doesn't make sense in real
ones.


>
> And AFAIK programs are not used anymore for teaching.
>
> At the end self.error(..) is just a shortcut for new Exception()
> You can do that directly.
>
> I find it weird to have an "error" object that is not an error and that
> only has a single method to throw errors.
>

I agree only if you already know classes. But up until then, all you have
is objects and messages, and error.throw(...) would be exactly that.
There's no new syntax to explain.

**Comment by matifreyre** [comment]
We already agreed that ```self``` in a program is not valid (and it's already implemented), so the original question is invalid now.
Will we add the error object? I vote yes.

**Comment by PalumboN** [comment]
Hi! I was thinking some comments:

> At the end self.error(..) is just a shortcut for new Exception()

No exactly, it was a shortcut for **throw** new Exception().

> I find it weird to have an "error" object that is not an error and that only has a single method to throw errors.

That's right! I'm agree.

So, the problem is that we want teach exceptions without instance an exception class. 
Why not, instead of have an object that throws exceptions, we have an object that is an exception, a generic exception.
For example:
```XTend
object error inherits Exception("Error") { }
```
Then we can do
```XTend
throw error
```

**Comment by javierfernandes** [comment]
Ha. Interesting.
Although been shared could be a problem because it has its stack 😬

**Comment by matifreyre** [comment]
You would still be introducing new syntax. I'd like to postpone the ```throw``` syntax and introduce it along with the corresponding catch. In the meantime, all I need is an object who knows how to break the program with a tidy message. That's why I still vote for error.throw(...)... 
Aaaaand the error object is already there in #834 and I would like to keep it :smile:. 
Please allow me!

**Comment by fdodino** [comment]
I was about to add a :+1: to Mati.
But I have a question: why use a error WKO and not a self.error("...") invocation in a WKO?
Every WKO inherits from Object...

Or is it inconvenient to say to the student

* Student: Where does that "error" method come from? Is not in our WKO...
* Teacher: Oh, sure. It's... it's somewhere... I can't explain it right now. Or well... WKO inherits from Objet class...
* Student: ??

Is that the point?

**Comment by matifreyre** [comment]
Just because you cannot use ```self``` directly in a program, that's all. 
It was discussed in this same issue... Yes, it's unlikely that you'll ever want to throw an error directly in a real program, but it's meant for very simple, introductory programs only.

**Comment by fdodino** [comment]
Ok, it is pointless to me to throw an error inside a program. 
But if we agree to use self.error inside a WKO, or self.error/throw in a class, and fail in a test, I don't mind having error WKO. 
I wouldn't teach it.

**Comment by fdodino** [comment]
Merging in 3 2 1...
:smile:

**Comment by PalumboN** [comment]
All it's ok for me. But

> You would still be introducing new syntax. I'd like to postpone the throw syntax and introduce it along with the corresponding catch. In the meantime, all I need is an object who knows how to break the program with a tidy message. That's why I still vote for error.throw(...)... 

I'm not agree. If I want teach how throw an exception I want introduce `throw` syntax, because that is the way. (Like the `if`, I don't want first go for a method and then change it later).

It's just a little comment, I don't know what option is better for the class.

**Comment by flbulgarelli** [comment]
@PalumboN I disagree. I personally don't want to introduce a special syntax if it is not necessary. Moreover, the throw syntax requires understanding about exception classes, which is not a core idea of the exception mechanism. I want to just focus on the exception bubbling at first.  Proper exception handling can be introduced latter. 

_Actually I am really for minimizing special syntax scenarios in an educational language. Does it help to have a totally different syntax for throwing exceptions? I hardly think so, but I but that is a matter we don't want to discuss right now :smile:_
