### ISSUE TITLE
Weird warnings on rename

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#712]
If I try to rename the following `baz2` method to `baz`: 

```
object foo {

	method baz2() {
		var x = 9
		return x * 3 + 7
	}
}


program abc {
	console.println(null + "hello")
}	
```

I get the following bad warnings: 

![wollokrename](https://cloud.githubusercontent.com/assets/677436/15906510/89fd8c2e-2d8f-11e6-98ce-d2c0f8aa17f2.png)

But there are no such syntax errors!

PS: it also shows a missconfigured language message, related to #674

**Comment by fdodino** [comment]
I could not get this error, because

- no Refactor rename was available
- and when I tried to use Alt - Shift - R, I got a "null" dialog message

```
java.lang.NullPointerException
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.encode(LazyURIEncoder.java:81)
	at org.eclipse.xtext.linking.lazy.LazyLinker.createProxy(LazyLinker.java:204)
	at org.eclipse.xtext.linking.lazy.LazyLinker.createAndSetProxy(LazyLinker.java:191)
	at org.eclipse.xtext.linking.lazy.SyntheticLinkingSupport.createAndSetProxy(SyntheticLinkingSupport.java:42)
	at org.uqbar.project.wollok.linking.WollokLinker.installProxies(WollokLinker.java:36)
	at org.eclipse.xtext.linking.lazy.LazyLinker$2.process(LazyLinker.java:103)
	at org.eclipse.xtext.linking.lazy.LazyLinker$2.process(LazyLinker.java:1)
	at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:37)
	at org.eclipse.xtext.util.OnChangeEvictingCache.execWithoutCacheClear(OnChangeEvictingCache.java:129)
	at org.eclipse.xtext.linking.lazy.LazyLinker.doLinkModel(LazyLinker.java:93)
	at org.eclipse.xtext.linking.impl.AbstractCleaningLinker.linkModel(AbstractCleaningLinker.java:51)
	at org.eclipse.xtext.resource.XtextResource.doLinking(XtextResource.java:323)
	at org.eclipse.xtext.resource.XtextResource.updateInternalState(XtextResource.java:284)
	at org.eclipse.xtext.resource.XtextResource.updateInternalState(XtextResource.java:273)
	at org.eclipse.xtext.resource.XtextResource.doLoad(XtextResource.java:171)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1518)
	at org.uqbar.project.wollok.ui.console.highlight.WollokCodeHighLightLineStyleListener$14.apply(WollokCodeHighLightLineStyleListener.java:321)
	at org.uqbar.project.wollok.ui.console.highlight.WollokCodeHighLightLineStyleListener$14.apply(WollokCodeHighLightLineStyleListener.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.uqbar.project.wollok.ui.console.highlight.WollokCodeHighLightLineStyleListener.parseIt(WollokCodeHighLightLineStyleListener.java:327)
	at org.uqbar.project.wollok.ui.console.highlight.WollokCodeHighLightLineStyleListener.lineGetStyle(WollokCodeHighLightLineStyleListener.java:128)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:49)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1327)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1351)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1336)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1117)
	at org.eclipse.swt.custom.StyledText.sendLineEvent(StyledText.java:8185)
	at org.eclipse.swt.custom.StyledText.getLineStyleData(StyledText.java:4208)
	at org.eclipse.swt.custom.StyledTextRenderer.getTextLayout(StyledTextRenderer.java:783)
	at org.eclipse.swt.custom.StyledTextRenderer.getTextLayout(StyledTextRenderer.java:708)
	at org.eclipse.swt.custom.StyledTextRenderer.calculate(StyledTextRenderer.java:211)
	at org.eclipse.swt.custom.StyledTextRenderer.getLineHeight(StyledTextRenderer.java:557)
	at org.eclipse.swt.custom.StyledText.getLineIndex(StyledText.java:4274)
	at org.eclipse.swt.custom.StyledText.getPartialBottomIndex(StyledText.java:4531)
	at org.eclipse.swt.custom.StyledText.getOffsetAtPoint(StyledText.java:4486)
	at org.eclipse.swt.custom.StyledText.getOffsetAtLocation(StyledText.java:4433)
	at org.eclipse.ui.console.TextConsoleViewer.mouseMove(TextConsoleViewer.java:601)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:212)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1327)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3819)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3430)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
```

Followed by 

```
Exception occurred while unrendering: org.eclipse.e4.ui.model.application.ui.basic.impl.PartStackImpl@68f32020 (elementId: stickyFolderRight, tags: [], contributorURI: null) (widget: CTabFolder {}, renderer: org.eclipse.e4.ui.workbench.renderers.swt.StackRenderer@234cd86c, toBeRendered: false, onTop: false, visible: true, containerData: 2500, accessibilityPhrase: null)
```

**Comment by fdodino** [comment]
Related to #697 

It happens because RefactoringCrossReferenceSerializer is checking whether new name has correct syntax.

``` java
	public String getCrossRefText(EObject owner, CrossReference crossref, EObject target,
			RefTextEvaluator refTextEvaluator, ITextRegion linkTextRegion, StatusWrapper status) {
		try {
			final EReference ref = GrammarUtil.getReference(crossref, owner.eClass());
			final IScope scope = scopeProvider.getScope(owner, ref);
			if (scope == null) {
				throw new IllegalStateException("Could not create scope for the given cross reference.");
			}
			String ruleName = linkingHelper.getRuleNameFrom(crossref);

			Iterable<IEObjectDescription> descriptionsForCrossRef = scope.getElements(target);
			String bestRefText = null;
			for (IEObjectDescription desc : descriptionsForCrossRef) {
				try {
					String unconvertedRefText = qualifiedNameConverter.toString(desc.getName());
					String convertedRefText = valueConverter.toString(unconvertedRefText, ruleName);
					if (refTextEvaluator.isValid(desc) && (bestRefText == null || refTextEvaluator.isBetterThan(convertedRefText, bestRefText)))
						bestRefText = convertedRefText;
				} catch (ValueConverterException e) {
					status.add(RefactoringStatus.WARNING,
							"Missconfigured language: New reference text has invalid syntax.", owner, linkTextRegion);
				}
			}
			return bestRefText;

		} catch (Exception exc) {
			log.error(exc.getMessage(), exc);
			status.add(ERROR, exc.getMessage(), owner, linkTextRegion);
			return null;
		}
	}
```

The problem is here: scope.getElements(target);
you probably get in this case a list: [x, foo.x]  (or something similar).
It works in the first case (that's why rename occurs), but afterwards you get several warnings, one for each indirection in the list (character "." makes it fail, because it doesn't conform a valid ID rule).
@tesonep  I don't know if we can override scope for WollokGlobalScopeProvider.

**Comment by fdodino** [comment]
Hi @tesonep , tried to talk to you, maybe tomorrow, I was able to fix this warning by commenting parent elements from Wollok import scope:

```xtend
	override getElements(EObject object) {
		synchronized (this) {
			val localElementsFound = if(localElements === null) #[] else localElements.getExportedObjectsByObject(object)
			localElementsFound //+ parent.getElements(object)
		}
	}
```

See parent.getElements(object).
I imported current TP and it seems to work, but it scares me to put such major change  before deploy.
