### ISSUE TITLE
[Weird behavior] Null is a null object? 

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/wollok#716]
Hi!

I found no reference about this behavior in [the wiki](https://github.com/uqbar-project/wollok/wiki/LanguageReference) , but it seems like adding or substracting nulls actually work. Other arithmetic operation works in unexpected ways, and other messages fails in weird ways. 

Some examples that show the heavy inconsistencies: 

 ```
[36;1mConsola Interactiva de Wollok (escriba "quit" para salir): [m
[36m>>> [m10 + null
[34m10[m
[36m>>> [m10 * null
[34mnull[m
[36m>>> [mnull.toString()
[31mwollok.lang.Exception: Cannot send message toString() to null
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/metodos.wlk:2]
[m
[36m>>> [m5.toString()
[34m5[m
[36m>>> [m5.toString().kindName()
[34mun/a  String[m
[36m>>> [mnull.methods()
[31mwollok.lang.Exception: Cannot send message methods() to null
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/metodos.wlk:2]
[m
[36m>>> [mnull / 3
     [31mError de la VM de Wollok en la linea (1): null / 3:[m
[31mjava.lang.NullPointerException
	at org.uqbar.project.wollok.interpreter.operation.WollokDeclarativeNativeBasicOperations$3.apply(WollokDeclarativeNativeBasicOperations.java:97)
	at org.uqbar.project.wollok.interpreter.operation.WollokDeclarativeNativeBasicOperations$3.apply(WollokDeclarativeNativeBasicOperations.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:717)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:168)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:236)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:132)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:139)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:1)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:627)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:536)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evalAll(WollokInterpreterEvaluator.java:142)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:187)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:214)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:236)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:132)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator._evaluate(WollokLauncherInterpreterEvaluator.java:68)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:212)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.interpret(WollokInterpreter.java:149)
	at org.uqbar.project.wollok.launch.repl.WollokRepl.executeInput(WollokRepl.java:164)
	at org.uqbar.project.wollok.launch.repl.WollokRepl.startRepl(WollokRepl.java:86)
	at org.uqbar.project.wollok.launch.WollokLauncher.doSomething(WollokLauncher.java:47)
	at org.uqbar.project.wollok.launch.WollokChecker.doMain(WollokChecker.java:83)
	at org.uqbar.project.wollok.launch.WollokLauncher.main(WollokLauncher.java:31)
[m
[36m>>> [mnull || true
     [31mError de la VM de Wollok en la linea (1): null || true:[m
[31morg.uqbar.project.wollok.interpreter.WollokRuntimeException: Error while resolving  || org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$11@61c4fc34
	at org.uqbar.project.wollok.interpreter.operation.WollokDeclarativeNativeBasicOperations$2.apply(WollokDeclarativeNativeBasicOperations.java:79)
	at org.uqbar.project.wollok.interpreter.operation.WollokDeclarativeNativeBasicOperations$2.apply(WollokDeclarativeNativeBasicOperations.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:717)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:168)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:236)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:132)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:139)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:1)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:627)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:536)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evalAll(WollokInterpreterEvaluator.java:142)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:187)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:214)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:236)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:132)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator._evaluate(WollokLauncherInterpreterEvaluator.java:68)
	at org.uqbar.project.wollok.launch.WollokLauncherInterpreterEvaluator.evaluate(WollokLauncherInterpreterEvaluator.java:212)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:1)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.interpret(WollokInterpreter.java:149)
	at org.uqbar.project.wollok.launch.repl.WollokRepl.executeInput(WollokRepl.java:164)
	at org.uqbar.project.wollok.launch.repl.WollokRepl.startRepl(WollokRepl.java:86)
	at org.uqbar.project.wollok.launch.WollokLauncher.doSomething(WollokLauncher.java:47)
	at org.uqbar.project.wollok.launch.WollokChecker.doMain(WollokChecker.java:83)
	at org.uqbar.project.wollok.launch.WollokLauncher.main(WollokLauncher.java:31)
Caused by: java.lang.NullPointerException
	at org.uqbar.project.wollok.interpreter.operation.WollokDeclarativeNativeBasicOperations.orOperation(WollokDeclarativeNativeBasicOperations.java:238)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.uqbar.project.wollok.interpreter.operation.WollokDeclarativeNativeBasicOperations$2.apply(WollokDeclarativeNativeBasicOperations.java:62)
	... 25 more
[m
[36m>>> [mnull.equals(8)
[31mwollok.lang.Exception: Cannot send message equals(8) to null
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/__synthetic0.wpgm:3]
	at  [/metodos.wlk:2]
[m
[36m>>> [mnull == 8
[34mfalse[m
[36m>>> [m
```

**Comment by flbulgarelli** [comment]
In brief:

* adding or subtracting null treats it as zero
* multiplying null answers null
* diving, &&, || nulls throws JavaExceptions
* sending custom unknown messages throws DNU Wollok exception - :+1: 
* `null.equals` is not understood, but `==` is. 

:scream:

**Comment by fdodino** [comment]
I think == and != should be understood by null.

**Comment by fdodino** [comment]
Tried null++ and it throws a correct validation error:

```
java.lang.AssertionError: Expected no errors, but got :ERROR (null) '++can only be applied to variable references' on WPostfixOperation, offset 43, length 4

	at org.junit.Assert.fail(Assert.java:88)
	at org.eclipse.xtext.junit4.validation.ValidationTestHelper.assertNoErrors(ValidationTestHelper.java:187)
	at org.eclipse.xtext.junit4.validation.ValidationTestHelper.assertNoErrors(ValidationTestHelper.java:48)
	at org.uqbar.project.wollok.tests.interpreter.AbstractWollokInterpreterTestCase.lambda$6(AbstractWollokInterpreterTestCase.java:166)
	at org.uqbar.project.wollok.tests.interpreter.AbstractWollokInterpreterTestCase$$Lambda$3/1123236701.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.uqbar.project.wollok.tests.interpreter.AbstractWollokInterpreterTestCase.lambda$5(AbstractWollokInterpreterTestCase.java:168)
	at org.uqbar.project.wollok.tests.interpreter.AbstractWollokInterpreterTestCase$$Lambda$2/1943855334.apply(Unknown Source)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.uqbar.project.wollok.tests.interpreter.AbstractWollokInterpreterTestCase.interpret(AbstractWollokInterpreterTestCase.java:194)
	at org.uqbar.project.wollok.tests.interpreter.AbstractWollokInterpreterTestCase.interpret(AbstractWollokInterpreterTestCase.java:150)
	at org.uqbar.project.wollok.tests.interpreter.AbstractWollokInterpreterTestCase.interpret(AbstractWollokInterpreterTestCase.java:146)
	at org.uqbar.project.wollok.tests.interpreter.AbstractWollokInterpreterTestCase.interpretPropagatingErrors(AbstractWollokInterpreterTestCase.java:114)
	at org.uqbar.project.wollok.tests.interpreter.AbstractWollokInterpreterTestCase.interpretPropagatingErrors(AbstractWollokInterpreterTestCase.java:90)
	at org.uqbar.project.wollok.tests.interpreter.AbstractWollokInterpreterTestCase.test(AbstractWollokInterpreterTestCase.java:102)
	at org.uqbar.project.wollok.tests.interpreter.NullTestCase.plusPlusOperatorSentToNull(NullTestCase.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.eclipse.xtext.junit4.XtextRunner$1.evaluate(XtextRunner.java:49)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by fdodino** [comment]
The same error for

```
const pepita
assert.throwsException({ pepita++ })
```
