### ISSUE TITLE
UndeclaredThrowableException while debugging

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok#852]
![image](https://cloud.githubusercontent.com/assets/4549002/17161639/81118748-5385-11e6-9c4a-1ed2e48aed13.png)

Problem occurred when launching debugger and sending a message to shrek.misionesDificiles()
See project 03-heroes-con-objetos in https://github.com/uqbar-project/wollok-examples

**Comment by fdodino** [comment]
Same error with other projects. Set Timeout higher but no effect.
Error log shows this trace

eclipse.buildId=unknown
java.version=1.8.0_45
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  /home/fernando/workspaces/wollok-examples
Command-line arguments:  -data /home/fernando/workspaces/wollok-examples -os linux -ws gtk -arch x86_64 /home/fernando/workspaces/wollok-examples

org.eclipse.core.jobs
Error
Tue Jul 26 23:11:57 ART 2016
An internal error occurred during: "Check Debug Command".

java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy49.getStackFrames(Unknown Source)
	at org.uqbar.project.wollok.debugger.WollokDebugTarget.getStackFrames(WollokDebugTarget.java:310)
	at org.uqbar.project.wollok.debugger.model.WollokThread.getStackFrames(WollokThread.java:34)
	at org.uqbar.project.wollok.debugger.model.WollokThread.canStepReturn(WollokThread.java:156)
	at org.eclipse.debug.internal.core.commands.StepReturnCommand.isSteppable(StepReturnCommand.java:27)
	at org.eclipse.debug.internal.core.commands.StepCommand.isExecutable(StepCommand.java:46)
	at org.eclipse.debug.core.commands.AbstractDebugCommand$UpdateJob.run(AbstractDebugCommand.java:101)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786)
	at java.io.ObjectOutputStream.reset(ObjectOutputStream.java:503)
	at net.sf.lipermi.handler.ConnectionHandler.sendMessage(ConnectionHandler.java:182)
	at net.sf.lipermi.handler.ConnectionHandler.remoteInvocation(ConnectionHandler.java:207)
	at net.sf.lipermi.handler.CallProxy.invoke(CallProxy.java:58)
	... 8 more

**Comment by fdodino** [comment]
Same error in Windows with default empty project ex.sayHi()

**Comment by javierfernandes** [comment]
I tested with with some other code and it worked fine.
So, it is something that only appears with this example.
Actually in the mac version the error is different (similar dialog but with a NPE).

**Comment by javierfernandes** [comment]
This is the different error that I'm seeing
<img width="439" alt="screen shot 2016-08-01 at 22 09 32" src="https://cloud.githubusercontent.com/assets/4428120/17313735/b80a8f3e-5834-11e6-8f7d-cd8dee91cb5e.png">

And this is the stack trace on the original dev eclipse

```java
!STACK 0
java.lang.NullPointerException
	at org.uqbar.project.wollok.debugger.server.rmi.XWollokListDebugValue.getElements(XWollokListDebugValue.java:55)
	at org.uqbar.project.wollok.debugger.server.rmi.XWollokListDebugValue.<init>(XWollokListDebugValue.java:40)
	at org.uqbar.project.wollok.debugger.server.rmi.XDebugStackFrameVariable.asRemoteValue(XDebugStackFrameVariable.java:41)
	at org.uqbar.project.wollok.debugger.server.rmi.XDebugStackFrameVariable.<init>(XDebugStackFrameVariable.java:33)
	at org.uqbar.project.wollok.debugger.server.rmi.XDebugStackFrame.toVariable(XDebugStackFrame.java:55)
	at org.uqbar.project.wollok.debugger.server.rmi.XDebugStackFrame.lambda$1(XDebugStackFrame.java:46)
	at org.uqbar.project.wollok.debugger.server.rmi.XDebugStackFrame$$Lambda$110/2030396842.apply(Unknown Source)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:794)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at com.google.common.collect.Iterators.addAll(Iterators.java:357)
	at com.google.common.collect.Lists.newArrayList(Lists.java:146)
	at com.google.common.collect.Lists.newArrayList(Lists.java:128)
	at org.uqbar.project.wollok.debugger.server.rmi.XDebugStackFrame.debugVariables(XDebugStackFrame.java:49)
	at org.uqbar.project.wollok.debugger.server.rmi.XDebugStackFrame.<init>(XDebugStackFrame.java:34)
	at org.uqbar.project.wollok.debugger.server.rmi.DebugCommandHandlerImpl.lambda$0(DebugCommandHandlerImpl.java:91)
	at org.uqbar.project.wollok.debugger.server.rmi.DebugCommandHandlerImpl$$Lambda$35/1105574192.apply(Unknown Source)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:572)
	at java.util.AbstractList$Itr.next(AbstractList.java:358)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
	at java.util.ArrayList.<init>(ArrayList.java:177)
	at com.google.common.collect.Lists.newArrayList(Lists.java:128)
	at org.uqbar.project.wollok.debugger.server.rmi.DebugCommandHandlerImpl.getStackFrames(DebugCommandHandlerImpl.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.sf.lipermi.handler.CallHandler.delegateCall(CallHandler.java:107)
	at net.sf.lipermi.handler.ConnectionHandler$1.run(ConnectionHandler.java:140)
	at java.lang.Thread.run(Thread.java:745)
```
