### ISSUE TITLE
Can't create anonymous object on REPL

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok#860]
When you write `object` in REPL it stop and the IDE shows weird.

**Comment by Juancete** [comment]
It happens in WollokCodeHighLightLineStyleListener at method parseIt when content have a program with the **object** word

Seems to have a problem with WollokLinker when tries to createAndSetProxy but i don't know why. Any Ideas?

!ENTRY org.eclipse.ui 4 0 2016-08-14 20:20:57.081
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.getRelativePath(LazyURIEncoder.java:209)
	at org.eclipse.xtext.linking.lazy.LazyURIEncoder.encode(LazyURIEncoder.java:81)
	at org.eclipse.xtext.linking.lazy.LazyLinker.createProxy(LazyLinker.java:204)
	at org.eclipse.xtext.linking.lazy.LazyLinker.createAndSetProxy(LazyLinker.java:191)
	at org.eclipse.xtext.linking.lazy.SyntheticLinkingSupport.createAndSetProxy(SyntheticLinkingSupport.java:42)
	**at org.uqbar.project.wollok.linking.WollokLinker.installProxies(WollokLinker.java:30)**
	at org.eclipse.xtext.linking.lazy.LazyLinker$2.process(LazyLinker.java:103)
	at org.eclipse.xtext.linking.lazy.LazyLinker$2.process(LazyLinker.java:1)
	at org.eclipse.xtext.util.concurrent.IUnitOfWork$Void.exec(IUnitOfWork.java:37)
	at org.eclipse.xtext.util.OnChangeEvictingCache.execWithoutCacheClear(OnChangeEvictingCache.java:129)
	at org.eclipse.xtext.linking.lazy.LazyLinker.doLinkModel(LazyLinker.java:93)
	at org.eclipse.xtext.linking.impl.AbstractCleaningLinker.linkModel(AbstractCleaningLinker.java:51)
	at org.eclipse.xtext.resource.XtextResource.doLinking(XtextResource.java:323)
	at org.eclipse.xtext.resource.XtextResource.updateInternalState(XtextResource.java:284)
	at org.eclipse.xtext.resource.XtextResource.updateInternalState(XtextResource.java:273)
	at org.eclipse.xtext.resource.XtextResource.doLoad(XtextResource.java:171)
	at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1518)
	at org.uqbar.project.wollok.ui.console.highlight.WollokCodeHighLightLineStyleListener$14.apply(WollokCodeHighLightLineStyleListener.java:321)
	at org.uqbar.project.wollok.ui.console.highlight.WollokCodeHighLightLineStyleListener$14.apply(WollokCodeHighLightLineStyleListener.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at **org.uqbar.project.wollok.ui.console.highlight.WollokCodeHighLightLineStyleListener.parseIt(WollokCodeHighLightLineStyleListener.java:327)**

**Comment by Juancete** [comment]
Any suggestions ?? @javierfernandes @tesonep

**Comment by tesonep** [comment]
pffffffffff, I don't know, I will see what is trying to do.

**Comment by fdodino** [comment]
I remember @javierfernandes found a workaround, but later some additional problems arised. I think we should try to fix it, what do you think @tesonep @npasserini ?

**Comment by tesonep** [comment]
I will see the proposed solution of @javierfernandes, the changes looks alright. But I will have to integrated as soon as the build process is back on green.

**Comment by fdodino** [comment]
Yeah @tesonep  is back!!! Watch out this, @Juancete !!
