### ISSUE TITLE
Conversion error in wollok list "addAll()" method

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/wollok#92]
This program:

```
	program p {
			val unos = #[1,2,3,4]
			val otros = #[5,6,7,8]
			
			val todos = #[]
			todos.addAll(unos)
			todos.addAll(otros)			
			this.assertEquals(8, todos.size())
		}
```

Produces the following error:

```
org.uqbar.project.wollok.interpreter.WollokInterpreterException: Error evaluating line __synthetic0.wpgm:[1]: program p {
	val unos = #[1,2,3,4]
	val otros = #[5,6,7,8]
	
	val todos = #[]
	todos.addAll(unos)
	todos.addAll(otros)			
	this.assertEquals(8, todos.size())
}
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:192)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:122)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:152)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:669)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.interpret(WollokInterpreter.java:101)
	at org.uqbar.project.wollok.tests.interpreter.AbstractWollokInterpreterTestCase$3$2.apply(AbstractWollokInterpreterTestCase.java:120)
	at org.uqbar.project.wollok.tests.interpreter.AbstractWollokInterpreterTestCase$3$2.apply(AbstractWollokInterpreterTestCase.java:1)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:362)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:331)
	at org.uqbar.project.wollok.tests.interpreter.AbstractWollokInterpreterTestCase$3.apply(AbstractWollokInterpreterTestCase.java:123)
	at org.uqbar.project.wollok.tests.interpreter.AbstractWollokInterpreterTestCase$3.apply(AbstractWollokInterpreterTestCase.java:1)
	at org.eclipse.xtext.xbase.lib.ObjectExtensions.operator_doubleArrow(ObjectExtensions.java:139)
	at org.uqbar.project.wollok.tests.interpreter.AbstractWollokInterpreterTestCase.interpret(AbstractWollokInterpreterTestCase.java:126)
	at org.uqbar.project.wollok.tests.interpreter.AbstractWollokInterpreterTestCase.interpretPropagatingErrors(AbstractWollokInterpreterTestCase.java:77)
	at org.uqbar.project.wollok.tests.interpreter.AbstractWollokInterpreterTestCase.interpretPropagatingErrors(AbstractWollokInterpreterTestCase.java:73)
	at org.uqbar.project.wollok.tests.interpreter.collections.RemoveTest.testAddAll(RemoveTest.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.eclipse.xtext.junit4.XtextRunner$1.evaluate(XtextRunner.java:49)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.junit4.runtime.patch.JUnit4TestReference.run(JUnit4TestReference.java:42)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.uqbar.project.wollok.interpreter.WollokInterpreterException: Error evaluating line __synthetic0.wpgm:[6]: todos.addAll(unos)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:192)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.eval(WollokInterpreterEvaluator.java:122)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:128)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator$1.apply(WollokInterpreterEvaluator.java:1)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:626)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:534)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evalAll(WollokInterpreterEvaluator.java:131)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:169)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:663)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:180)
	... 41 more
Caused by: java.lang.RuntimeException: Cannot convert parameter "WList[1, 2, 3, 4]" to type "Collection""
	at org.uqbar.project.wollok.ui.utils.XTendUtilExtensions.convertTo(XTendUtilExtensions.java:387)
	at org.uqbar.project.wollok.ui.utils.XTendUtilExtensions$8.apply(XTendUtilExtensions.java:305)
	at org.uqbar.project.wollok.ui.utils.XTendUtilExtensions$8.apply(XTendUtilExtensions.java:1)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.fold(IteratorExtensions.java:626)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.fold(IterableExtensions.java:534)
	at org.uqbar.project.wollok.ui.utils.XTendUtilExtensions.invokeConvertingArgs(XTendUtilExtensions.java:312)
	at org.uqbar.project.wollok.ui.utils.XTendUtilExtensions.invoke(XTendUtilExtensions.java:250)
	at org.uqbar.project.wollok.interpreter.nativeobj.AbstractWollokWrapperNativeObject.doesNotUnderstand(AbstractWollokWrapperNativeObject.java:31)
	at org.uqbar.project.wollok.interpreter.nativeobj.AbstractWollokDeclarativeNativeObject.call(AbstractWollokDeclarativeNativeObject.java:35)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._call(WollokInterpreterEvaluator.java:603)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.call(WollokInterpreterEvaluator.java:691)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.perform(WollokInterpreterEvaluator.java:599)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator._evaluate(WollokInterpreterEvaluator.java:569)
	at org.uqbar.project.wollok.interpreter.WollokInterpreterEvaluator.evaluate(WollokInterpreterEvaluator.java:667)
	at org.uqbar.project.wollok.interpreter.WollokInterpreter.eval(WollokInterpreter.java:180)
	... 50 more


```

**Comment by javierfernandes** [comment]
@dfortini
